### ISSUE TITLE
parameters in edit distance (dp)

### ISSUE THREAD

**Issue by shadrak98** [TheAlgorithms/C-Plus-Plus#100]
instead of (str1, str1, ....) on 83 & 84 it should be (str1, str2, ....) on both lines

**Comment by mrdogan7** [comment]
In [C-Plus-Plus/Sorting/Insertion Sort.cpp](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/Sorting/Insertion%20Sort.cpp) , n is declared but not defined or taken as an input. 
To fix it, 
   `cin>>n;`
should be added between line 8 and 9.
