### ISSUE TITLE
[FEATURE] Graph namespace

### ISSUE THREAD

**Issue by fhlasek** [TheAlgorithms/C-Plus-Plus#1005]
Refactor the graph algorithms to a separate `graph` namespace.

## Detailed Description
Most of the code in the graph subfolder lives in the global namespace. It would be preferable to have the functions transfer into a separate namespace.

## Context
Suggested in #980, contributes to #909.

## Possible Implementation
https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/graph/breadth_first_search.cpp#L56

**Comment by Panquesito7** [comment]
I think this issue has been fixed. If you think this needs to be re-opened, please re-open it. Thank you.
