### ISSUE TITLE
Pancake Sort

### ISSUE THREAD

**Issue by divyansh12323** [TheAlgorithms/C-Plus-Plus#1008]
## Aim
 Sort a disordered stack of N  pancakes in order of size with minimum number of flips when a spatula can be inserted at any point in the stack and used to flip all pancakes above it .

P.S. I'm working on it

**Comment by kvedala** [comment]
Thank you 👍 
Please ensure to follow the documentation standard and a generic structure for the code [like this, for example](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/sorting/gnome_sort.cpp)

**Comment by aashigupta19** [comment]
Hey, I and my team would also like to work on this issue. Can you please assign us this?? @kvedala @divyansh12323

**Comment by nikhilkala** [comment]
@aashigupta19 
You can work on this issue, or any issue as a matter of fact, no need to ask. Just look into the contribution guidelines to get going.

**Comment by aashigupta19** [comment]
Heyy, actually we required some user acceptance tests for our ongoing project too, like what should be the exact required output, for utmost clarity of the issue, so can you provide the same if possible? Or shall we proceed with our own test cases?? @nikhilkala @divyansh12323 @kvedala

**Comment by divyansh12323** [comment]
Hey , I was busy with my university exams and couldn't complete the issue but i had made significant progress so I would like to continue on this issue. Can you please assign this to me? @kvedala @nikhilkala

**Comment by kvedala** [comment]
No need to assign. Feel free to contribute with a pull-request. But do ensure the following:
1. that the code does not already exist in the repo
2. review contribution guidelines for the repo
3. all automated checks must pass.
