### ISSUE TITLE
Implement Palindrome Partitioning algorithm

### ISSUE THREAD

**Issue by sujaykaushik008** [TheAlgorithms/C-Plus-Plus#1009]
### Aim
To implement an algorithm that gives, the minimum no. of partitions you will have to do in a string, such that each resultant sub string will be a palindrome.

ex: for a given string S: "NITIK" we can do the partition as -  N | ITI | K thus, output will be "2" (without quotes)

PS: I will be working on the implementation

**Comment by ridhishjain** [comment]
I don't know..is this somehow similar to cutting-rod problem in DP?

**Comment by Ritikjain999** [comment]
Hey! I would like to work on this issue please assign it to me
