### ISSUE TITLE
Implementation of Ternary Search using C++

### ISSUE THREAD

**Issue by VasuSehgal123** [TheAlgorithms/C-Plus-Plus#1012]
## Aim

To implement Ternary Search algorithm in search directory using C++.

PS: I will be working on this.

**Comment by Panquesito7** [comment]
Thank you for your contribution on this. 👍
In your PR, please add proper documentation and refined code like in #962.

**Comment by VasuSehgal123** [comment]
Thank you for your review, I will start working on this.

**Comment by adi-g15** [comment]
@Panquesito7 @VasuSehgal123  this issue can be closed, as it is already implemented - https://github.com/TheAlgorithms/C-Plus-Plus/blob/8e14b25fa36042f89d13cc456d71f02f41ef6caa/search/ternary_search.cpp
