### ISSUE TITLE
Longest repeating subsequence

### ISSUE THREAD

**Issue by sainyagoyal** [TheAlgorithms/C-Plus-Plus#1015]
### AIM
Implement a program which print the longest repeating subsequence such that the two subsequence don’t have same string character at same position.
For eg: input:AABEBCDD    output:ABD

PS:I am working on

**Comment by Panquesito7** [comment]
Thank you for your contribution on this. 👍
In your PR, please add proper documentation and refined code like in #962.

**Comment by cfya** [comment]
I would like to work  on this @sainyagoyal @aashigupta19
