### ISSUE TITLE
[FEATURE]Delete without head pointer

### ISSUE THREAD

**Issue by rakshaa2000** [TheAlgorithms/C-Plus-Plus#1069]
You are given a pointer/ reference to the node which is to be deleted from the linked list of N nodes. The task is to delete the node. Pointer/ reference to the head node is not given. 

## Detailed Description

You only need to complete the function deleteNode that takes reference to the node that needs to be deleted. The printing is done automatically by the driver code.

## Context

I had encountered this algorithm in multiple coding contests and it intrigued me. I wanted to share this awesome algorithm.

**Comment by elit-altum** [comment]
@rakshaa2000 Can I try this one ? And this is for a singly linked list right?

**Comment by elit-altum** [comment]
I believe this function would work just fine
```cpp
void delete_node(node* del_node) {
  if (del_node == NULL || del_node->next == NULL) {
    return;
  }

  node* temp = del_node->next;
  node* curr = del_node;

  curr->data = temp->data;
  curr->next = temp->next;

  delete temp;
}
```

**Comment by kvedala** [comment]
This is valid for a C-implementation. In C++, use of STL classes completely avoids this problem.
