### ISSUE TITLE
[FEATURE]: MinHeap and MaxHeap algorithm

### ISSUE THREAD

**Issue by singhalshubham89** [TheAlgorithms/C-Plus-Plus#1082]
MinHeap and MaxHeap using priority queue is missing in Datastructure
## Detailed Description

Simple approach to perform minheap and maxheap using priorityqueue
## Context

I have used in many competitive contest 
## Possible Implementation

I can create PR creating sample use of priorityqueue

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

- The algorithm isn't a duplicate in this repository.
- Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
- Ensure that the all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by singhalshubham89** [comment]
Please review my pull request with #1121 with this feature. Please note this is my second contribution to open source, any feedback or change is appreciated.
