### ISSUE TITLE
[FEATURE] Subset sum problem

### ISSUE THREAD

**Issue by Bijoy-007** [TheAlgorithms/C-Plus-Plus#1099]
Subset sum problem
## Detailed Description

Subset sum is based on 0/1 knapsack and a fundamental problem of DP so I want to add it here

**Comment by Bijoy-007** [comment]
Can I work on this?

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that the all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by aashigupta19** [comment]
I also want to work on this issue. Can you please assign me this?

**Comment by Panquesito7** [comment]
Please read the [contributing guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#contributor): do **not** ask to be
assigned, instead, create a PR; project maintainers will review it. 🙂
