### ISSUE TITLE
3 way QuickSort(DNF Sort)

### ISSUE THREAD

**Issue by sawwwrabhp** [TheAlgorithms/C-Plus-Plus#1125]
Based on divide and conquer approach.
Higher overheads but it takes O(n) time for O(1) unique keys. So it is used when working with arrays with large number of duplicates.

**Comment by sawwwrabhp** [comment]
Can i work on this?

**Comment by tanujdhiman** [comment]
Hey, @sawwwrabhp 
The Overall Time Complexity of quick Sort is O(nlogn). It differs in some cases:
* Worst Case - O(n^2)
* Best Case - O(nlogn)
* Average Case - O(nlogn)

Space Complexity of Quick Sort is O(nlogn).
These are the complexities of Basic Quick Sort. but you are talking different which has O(n) complexity.
Can you explain this clearly what approach and advantage of that ?

**Comment by kvedala** [comment]
there are already 2 implementations. Is this different from them? if so, how? 
READ GUIDELINES. It clearly mentions not to ask for "assigning" issues. Feel free to work on your time and send a pull-request.
