### ISSUE TITLE
[FEATURE] Gas Station Problem in C++

### ISSUE THREAD

**Issue by anjali1903** [TheAlgorithms/C-Plus-Plus#1183]
## Detailed Description
There is a car with an unlimited gas tank and it costs cost[i] of gas to travel from station i to its next station (i+1). We begin the journey with an empty tank at one of the gas stations.
The starting gas station's index is returned if one can travel around the circuit once in the clockwise direction, otherwise -1 is returned.

## Context
I would like to contribute to the repository by writing the code to this famous Greedy algorithm problem.

**Comment by kvedala** [comment]
you can simply create a pull-request when you have the code ready. creating stub issues is counterintuitive.
