### ISSUE TITLE
[Enhancement] missing bin of some directory after build

### ISSUE THREAD

**Issue by xgupta** [TheAlgorithms/C-Plus-Plus#1211]
## Description

When I build the project and see the <build> directory to check the output. Three directories namely greedy_algorithms, operations_on_datastructures, range_queries missing. There are no cmakelist.txt under these directories.

## Expected Behavior

Every directory should have produced its bin after the build.

## Actual Behavior

Three bin directories are missing.

## Possible Fix

Add respective cmakelist.txt files for them and include them in root cmakelist.txt.

## Steps to Reproduce

1. build the project in the build directory.
2. count the no. of directories in build.

**Comment by kvedala** [comment]
It is not so easy. The remaining folders were not included in the CMake build system because of the extensive number of changes required for the individual programs. You are more than welcome to contribute fixing the codes first and then we can add the CMakeLists.txt to the folder. I can create that as a GitHub repo project and the pull-requests can be added to it for better tracking.

**Comment by xgupta** [comment]
So we will create saperate pull requests for these three directories. we will first try to build greedy_algorithm directory. When configuring this directory with cmake by adding entry in root CmakeLists.txt and creating a CmakeLists.txt in greedy_algorithm directory, an error occured 

> add_executable cannot create target "dijkstra" because another target with
> the same name already exists.  The existing target is an executable created
> in source directory "/home/xgupta/dev/C-Plus-Plus/graph"

So to fix it we can change the name of greedy_algorithms/dijkstra.cpp to something like greedy_algorithms/dijkstra_spf.cpp. where spf expand to shortest path first. 
When I do it greedy_algorithms bin created in the build without any error. 
So I am sending first pull request to fix this directory, see [#1253](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1253)

**Comment by xgupta** [comment]
Any progress on this?
