### ISSUE TITLE
[FEATURE] I want to add some BITWISE algorithms to this repository

### ISSUE THREAD

**Issue by sri-vaishnav** [TheAlgorithms/C-Plus-Plus#1212]
// FINDING WEATHER ith BIT IS SET OR NOT

int get_i_bit( int NUMBER, int i)
{
    int bit_at_i = NUMBER & (1<<i); 
    return bit_at_i;   // returns 1 if the ith bit is 1 else return 0
}

// Making ith bit set

int set_i_bit(int NUMBER, int i)
{
    int set_at_i = (1<<i) | NUMBER; // ith bit of NUMBER is being set by this operation 
    return set_at_i;
}

// Making ith bit unset

int set_i_bit(int NUMBER, int i)

{
    if(NUMBER == 0)
    {
        return 0;
    }
    
    int set_at_i = ~(1<<i) & NUMBER; // ith bit of NUMBER is being set by this operation 
    return set_at_i;
}

/*
Given an array where every element occurs two times, except one element which occurs only once. Find the element that occurs once. Expected time complexity is O(n) and O(1) extra space.

*/
// Here we use XOR operator for this algorithms
// we know that x XOR x  = 0
// SO if we xor 0 with every element in th array then all elements occuring twice becomes zeros and we are left with the element that occurs once.

int element_occurs_once (int a[], int n)
{
    int x = 0;

    for(int i=0;i<n;i++)
    {
        x = x ^ a[i];
    }
    return x;
}

//Time complexity - O(n)
//Space complexity - O(1)

// Finding the position of rightmost set bit of a number

/*

ALgorithm :

1. Take two's complement of the given no as all bits are reverted
except the first '1' from right to left

2  Do a bit-wise & with original no, this will return no with the
required one only.

3  Take the log2 of the no

4  Add 1
*/

//Example : 12(1100)----:
/*
1. Take two's complement of the given no as all bits are reverted
except the first '1' from right to left (0100)

2  Do a bit-wise & with original no, this will return no with the
required one only (0100)

3  Take the log2 of the no, you will get (position - 1) (2)

4  Add 1 (3)

*/

//code:
#include<bits/stdc++.h>
int getFirstSetBitPos(int n)
{
    return log2(n & -n) + 1;
}

//Given a positive integer, a function to find if it is a power of two or not.

/*
If we subtract a power of 2 numbers by 1 then all unset bits after the only set bit become set;
 and the set bit becomes unset.
For example for 4 ( 100) and 16(10000), we get following after subtracting 1 
3 –> 011 
15 –> 01111
So, if a number n is a power of 2 then bitwise & of n and n-1 will be zero.
 We can say n is a power of 2 or not based on value of n&(n-1). 
 The expression n&(n-1) will not work when n is 0. 
 To handle this case also, our expression will become n& (!n&(n-1)) 
*/

bool isPowerOfTwo (int x) 
{ 
    /* First x in the below expression is for the case when x is 0 */
    return x && (!(x&(x-1))); 
}

// Smallest power of 2 greater than or equal to n
/*
 If n is a power of 2 then return n 
1  If (n & !(n&(n-1))) then return n 
2  Else keep right shifting n until it becomes zero and count no of shifts
    a. Initialize: count = 0
    b. While n ! = 0
            n = n>>1
            count = count + 1

 Now count has the position of set bit in result 
3  Return (1 << count)  
*/

//code :
int nextPowerOf2(int n)
{  
    int count = 0;  
      
    // First n in the below condition  
    // is for the case where n is 0  
    if (n && !(n & (n - 1)))  
        return n;  
      
    while( n != 0)  
    {  
        n >>= 1;  
        count += 1;  
    }  
      
    return 1 << count;  
}

// Timecomplexity : O(n)

/*
Given an array where every element occurs two times, except one element which occurs only once. Find the element that occurs once. Expected time complexity is O(n) and O(1) extra space.

*/
// Here we use XOR operator for this algorithms
// we know that x XOR x  = 0
// SO if we xor 0 with every element in th array then all elements occuring twice becomes zeros and we are left with the element that occurs once.

int element_occurs_once (int a[], int n)
{
    int x = 0;

    for(int i=0;i<n;i++)
    {
        x = x ^ a[i];
    }
    return x;
}

//Time complexity - O(n)
//Space complexity - O(1)

**Comment by kvedala** [comment]
Feel free to contribute with a pull-request. the Issue created here is moot as no action can be taken on it.
