### ISSUE TITLE
[Adding a Binary Tree Problem]

### ISSUE THREAD

**Issue by Aman23092001** [TheAlgorithms/C-Plus-Plus#1277]
Symmetric Tree | LeetCode | 101

## Detailed Description
I want to add a question on Binary Tree, which LeetCode famous problem Symmetric tree. This problem is solved using DFS

## Context
Well, I wanted to participate in hacktoberfest and so providing a value to the open source is always a good thing.
They can understand multiple topics like recursion, what is DFS. And also it will encourage them towards problem solving skills.

**Comment by kvedala** [comment]
To participate in the Octoberfest, 
1. create a contribution appropriate for this repo
2. Review the repo's aims and objectives and the coding standards. Lot of documentation and samples are provided.
3. Create a pull-request from your fork of this repo. Ensure you follow the checklist thoroughly. 

Creating issues does not help in Octoberfest. 
Thank you
