### ISSUE TITLE
[FEATURE] Can I comment on the algorithm part and translate the readme file into Korean?

### ISSUE THREAD

**Issue by ji-sang-geun** [TheAlgorithms/C-Plus-Plus#1283]
Can I comment on the algorithm part and translate the readme file into Korean...?

## Detailed Description

I want to comment on the code to make it easier for others to study and more readable.

## Context

If you translate the Readme, other Koreans can participate in code contributions and error detection. Also, by commenting, it's easy to see at a glance what those lines do.

**Comment by kvedala** [comment]
To maintain language specific translations for the entire repo would be quite difficult. All the documentations are within the code itself in English. The easier way to translate would be to add Google-Translate or appropriate option to the documentation site: https://thealgorithms.github.io/C-Plus-Plus
