### ISSUE TITLE
Algorithm to find number of inversions in an array

### ISSUE THREAD

**Issue by lordinkavu** [TheAlgorithms/C-Plus-Plus#1309]
An algorithm to find how many inversions are required to make an array sorted. This would give an idea on the degree to which the algorithm is already sorted.

**Comment by danglingP0inter** [comment]
Can you assign this issue to me?

**Comment by Ganesh-Agarwal-25** [comment]
please assign this to me

**Comment by aashigupta19** [comment]
Sir can you please assign this to me. We are a team of 11 members doing this project as part of our college(LNMIIT) curriculum,  so we'll be completing this project within 4 weeks.

**Comment by Panquesito7** [comment]
> please assign this to me

Please read the [contributing guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#contributor): do **not** ask to be
assigned, instead, submit a PR and maintainers will review it. 🙂

**Comment by tejasdeore7** [comment]
@Panquesito7 I have solved this issue. Please review my PR.
