### ISSUE TITLE
[FEATURE] Implement nCr mod p

### ISSUE THREAD

**Issue by KaustubhDamania** [TheAlgorithms/C-Plus-Plus#1323]
## Detailed Description

Implementation of (nCr % p)

## Context

It is a common subproblem in competitive programming questions.

**Comment by webdesignbydivyansh** [comment]
can u tell me what is p here?

**Comment by KaustubhDamania** [comment]
@webdesignbydivyansh p is a given integer, so the value of nCr can be large and not enough to fit even in 64 bit long long int, so in competitive programming, they ask to find value of nCr modulo p

**Comment by webdesignbydivyansh** [comment]
if I make a pull request, will that be counted for hacktober fest?

**Comment by KaustubhDamania** [comment]
> if I make a pull request, will that be counted for hacktober fest?
Yes, find some other issue and submit a pull request because I have submitted a PR for this issue

**Comment by Sreshth01** [comment]
Can I assume p is a prime number? As in most of the competitive programming problems, p is a large prime number.

**Comment by ayaankhan98** [comment]
[Already Implemented](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/ncr_modulo_p.cpp)
