### ISSUE TITLE
ArraySub

### ISSUE THREAD

**Issue by JayantGoel001** [TheAlgorithms/C-Plus-Plus#1433]
## Detailed Description
Given an array and an integer k, find the maximum for each and every contiguous subarray of size k.

## Context
(It shows implementation and algorithm of heap or deque data structure) 

## Possible Implementation
Use of deque STL library

**Comment by yashgoyal60** [comment]
If is not assigned to anyone and you are not working on this. Can I take this and send a merge request

**Comment by Panquesito7** [comment]
> Can I take this and send a merge request

Please wait a few more days. Usually it may take more than a week.
If that limit is passed, you're welcome to make a PR. Only ensure that:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that the all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

Thank you. 🙂

**Comment by JayantGoel001** [comment]
Hello @Panquesito7
Does someone assign me to this task or should I make PR without being assigned?
