### ISSUE TITLE
Palindrome Linkedlist in cpp

### ISSUE THREAD

**Issue by akrish4** [TheAlgorithms/C-Plus-Plus#1435]
## Detailed Description

I would like to add palindrome linkedlist program in cpp.
## Context

Since this topic is missing , I would like to add this topic.
## Possible Implementation

Using Linkedlist.

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that the all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by faraz16iqbal** [comment]
Hey can i work on this?

**Comment by ayaankhan98** [comment]
> Hey can i work on this?

sure go ahead

**Comment by faraz16iqbal** [comment]
Is there a time and space constraint?

**Comment by ayaankhan98** [comment]
> Is there a time and space constraint?

No there is no such constraint. 
Here we do not follow any competetive criteria to mesure the performance of Algorithms. The sole purpose of this repository to serve for educational purpose by providing generally used algorithm implementations using cpp best practices.

**Comment by akrish4** [comment]
open another one @faraz16iqbal
