### ISSUE TITLE
[FEATURE] Spiral Display of elements of 2-D array

### ISSUE THREAD

**Issue by japneetbhatia** [TheAlgorithms/C-Plus-Plus#1442]
## Detailed Description

Suppose the array is :
11 12 13 14 15
21 22 23 24 25
31 32 33 34 35
Output :
11 21 31 32 33 34 35 25 15 14 13 12 22 23 24

## Context

This is a Basic Problem in which we learn to run loops in 2-D array

## Possible Implementation
Arrays

**Comment by japneetbhatia** [comment]
I would like to work on this issue

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that the all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by ayaankhan98** [comment]
[Already Existing](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/others/spiral_print.cpp)
