### ISSUE TITLE
[BUG]: small bug in comb sort

### ISSUE THREAD

**Issue by anonymouss** [TheAlgorithms/C-Plus-Plus#1443]
https://github.com/TheAlgorithms/C-Plus-Plus/blob/e62e94dc2e723cde521cf0730e51046cca148796/sorting/comb_sort.cpp#L64

should be `i < r - gap`, otherwise, when `i = r - gap`, `arr[i + gap]` will be index out of bound.

btw, `swapped` flag seems to be redundant here in `while (gap != 1 || swapped) {}`, no matter `swapped` is `true` or `false`, loop ends when `gap == 1`

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* Check if there are no other PR's about this.
* Make your fixes as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that the all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by Panquesito7** [comment]
@ayaankhan98 please use squash-merge. Thank you. 🙂
