### ISSUE TITLE
[FEATURE] add integral function

### ISSUE THREAD

**Issue by Bro0x00** [TheAlgorithms/C-Plus-Plus#1469]
Add integral functionality
## Detailed Description

Add a function fnInt(...) that returns the approximate integral of some function on [a, b] (the function must be continuous on [a, b]). uses Riemann sum except with trapezoids rather than rectangles (for greater accuracy). 

## Context

Integrals have a lot of uses in many fields of mathematics.

## Possible Implementation

template<typename R, typename I> //R and I should be either float or double. R is return type, I is input type
R fnInt(I a, I b, R (*f)(I), I subdivisions) {
 R result;
 I dx = (b - a)/subdivisions;
 for(; a < b; a += dx) {
  result += 0.5*dx*(f(a) + f(a + dx)); //area of trapezoid
 }
 return result;
}

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by shiqisheng2036** [comment]
Hello, I am claiming this issue and working on it. Thank you.
