### ISSUE TITLE
Wanted to add Paint App in c++

### ISSUE THREAD

**Issue by UG-SEP** [TheAlgorithms/C-Plus-Plus#1474]
Hey,
I have cool project Paint With UG a Desktop application so can i add my project.
[Project Link](https://github.com/UG-SEP/Paint-with-UG-The-SEP)
```javascript
if(You Like Project)
{
So please give a star⭐
also assign me to add the project
and tell me that whether i have to add my project in graphics folder or  create a new folder 
if(New)
{
Tell me a suitable folder name
}
} 
```
Thanks

**Comment by Panquesito7** [comment]
Read the discussion here: https://github.com/TheAlgorithms/C/issues/826
