### ISSUE TITLE
feat: Implementation of Friend Pairing problem. Dynamic Programming

### ISSUE THREAD

**Issue by faizan2700** [TheAlgorithms/C-Plus-Plus#1476]

**Comment by faizan2700** [comment]
There is one problem of dynamic programming problem that each friend can go to some party single or pairing with another friend. Find the number of Ways N friends can go to party. Should I add the implementation in Dynamic Programming module.

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by faizan2700** [comment]
Thank You.
