### ISSUE TITLE
Whether a number is Kaprekar program in c++

### ISSUE THREAD

**Issue by UG-SEP** [TheAlgorithms/C-Plus-Plus#1482]
Please let me to add that whether a number is karpekar number of not 
Example:
`Input:` 128
`Output:` No,128 is not a Kaprekar number
`Input:` 9
`Output:` Yes, 9 is a Kaprekar number 
Wanted to add this program [here](https://github.com/TheAlgorithms/C-Plus-Plus/tree/master/math)
Please let me assign to do that 
Thanks

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

I'll look into your PR and review it as soon as I can. Thanks. 🙂

**Comment by UG-SEP** [comment]
> Thank you for your interest in contributing. 👍
> Before submitting a PR, please ensure the following:
> 
> * The algorithm isn't a duplicate in this repository.
> * Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
> * Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.
> 
> I'll look into your PR and review it as soon as I can. Thanks. 🙂

ok
