### ISSUE TITLE
[FEATURE] COMMIT AS MEMBER 

### ISSUE THREAD

**Issue by amino19** [TheAlgorithms/C-Plus-Plus#1490]
### Detailed Description

I have some documents in `.md` file, its necessary to get commit in Algorithm for more enhancement. 

### Context

One can use it in many way, as its from an organization name "Geeks for geeks", basically its paid but, I want to commit here as free for others learning docs. & gaining knowledge.

### Possible Implementation

I need to create one folder name "docs" for learner, as its contains `.md` files, so one can get basic idea to extracts learning material.

My proposal is for organization to have me in Algorithm team, so I can get more indulge in sharing resources. 😃 
But for this issue, I need your assignation & guidance, Pl share me link to join community (if any).

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
It's great to know you want to join the organization!

We already have a repository [Algorithms Explanation](https://github.com/TheAlgorithms/Algorithms-Explanation) where you can find explanations of many algorithms (if that's what you're asking for). 🙂

A few things you should do before joining:

- Contribute to one of our repositories (if possible constantly).
- Review other people's pull requests.
- Help find and fix issues.

Unfortunately, we won't accept invitation requests without contributing history in The Algorithms.
Anyways, we'd appreciate it if you'd join our Discord server of The Algorithms: https://discord.gg/c7MnfGFGa6

We'll try to help you if you got any questions, comments, or experiencing problems with something. Thank you! 🙂

**Comment by amino19** [comment]
Thanks David Sir, I think that's really great to go along with <a href="https://github.com/TheAlgorithms/Algorithms-Explanation/tree/master/en">Algorithm explaination</a>.
- I start my contributions today onwards (constantly)
- Sure, I'll review others PR also, & if its reliable to merge, I'll inform you..
- As member, I'll prove as an asset in every field, to the organization.

Once you read this, I request to close this issue, with assign me as a **member to org.**, so I can access everything.

**Comment by Panquesito7** [comment]
> with assign me as a **member to org.**, so I can access everything.

> Unfortunately, we won't accept invitation requests without contributing history in The Algorithms.

**Comment by amino19** [comment]
Just made a pull request, <a href="https://github.com/TheAlgorithms/Algorithms-Explanation/pulls">here</a>.
Pl verify!

**Comment by amino19** [comment]
How can I check whether, the program meets all aspects in my local computer?
By the way, I updated everything, as per requirements..

**Comment by amino19** [comment]
@Panquesito7  I think now, it satisfy the requirements!

**Comment by Panquesito7** [comment]
Closing as @amino19 is already a member. 🙂
