### ISSUE TITLE
[BUG] neural_network.cpp

### ISSUE THREAD

**Issue by shahbazsyed** [TheAlgorithms/C-Plus-Plus#1495]
Clarification regarding the implementation of dsigmoid and selection of activation function.
## Description

Same activation function used for sigmoid and its derivative
https://github.com/TheAlgorithms/C-Plus-Plus/blob/fed98e86403abb32181a4e5ce90810f0e8d2e3ac/machine_learning/neural_network.cpp#L146
https://github.com/TheAlgorithms/C-Plus-Plus/blob/fed98e86403abb32181a4e5ce90810f0e8d2e3ac/machine_learning/neural_network.cpp#L147
https://github.com/TheAlgorithms/C-Plus-Plus/blob/fed98e86403abb32181a4e5ce90810f0e8d2e3ac/machine_learning/neural_network.cpp#L187
https://github.com/TheAlgorithms/C-Plus-Plus/blob/fed98e86403abb32181a4e5ce90810f0e8d2e3ac/machine_learning/neural_network.cpp#L188

## Expected Behavior

`double dsigmoid(const double &x) { return sigmoid(x) * (1 - sigmoid(x)); }`
## Actual Behavior

Current code for `dsigmoid` (https://github.com/TheAlgorithms/C-Plus-Plus/blob/fed98e86403abb32181a4e5ce90810f0e8d2e3ac/machine_learning/neural_network.cpp#L67)
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The fix isn't a duplicate PR in the repository.
* Make your fix as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

I'll look forward to reviewing your PR as soon as I can. Thanks! 😄
