### ISSUE TITLE
[FEATURE] Divide and Conquer

### ISSUE THREAD

**Issue by AbhinavXT** [TheAlgorithms/C-Plus-Plus#1507]
Add a folder for Divide and Conquer algorithms.
## Detailed Description

Add a Divide and Conquer folder to for problems specific to this method.
## Context

C++ is one of the major languages used in competitive programming. So, I would like to contribute to this repository. 
## Possible Implementation

I would like to add divide and conquer problems and also their time and space complexity analysis.

**Comment by Swastyy** [comment]
Its a good idea btw we have many algorithms on divide and conquer role @Panquesito7

**Comment by Swastyy** [comment]
@Panquesito7 this is already fixed, I suppose it can closed now.
