### ISSUE TITLE
Addition in Backtracking

### ISSUE THREAD

**Issue by kirtisingh3008** [TheAlgorithms/C-Plus-Plus#1523]
## Detailed Description
Word Break problem and Remove Invalid Parentheses Problem are really good problems to be added under this topic.
Thought Word Break has other implementations too but can also be solved using backtracking.

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

I'll review your PR as soon as possible once it's submitted. Thanks. 🙂
