### ISSUE TITLE
[BUG] check_prime.cpp returns incorrect output for 9

### ISSUE THREAD

**Issue by codingbbq** [TheAlgorithms/C-Plus-Plus#1536]
## Description
If you check the number 9 for prime, it returns true.

## Expected Behavior
is_Prime(9) should return false

## Actual Behavior
is_Prime(9) should return true

## Possible Fix
Changes in the for loop ?

**Comment by mrvishalsharma** [comment]
I have fixed the bug.

//Before :- 

Enter the number to check if it is prime or not
9 is a prime number

// After
Enter the number to check if it is prime or not
9 is not a prime number
