### ISSUE TITLE
Update the projects list

### ISSUE THREAD

**Issue by Swastyy** [TheAlgorithms/C-Plus-Plus#1551]
### Detailed description

As we have already completed these below mentioned projects they should be removed from the `List to fix`.
https://github.com/TheAlgorithms/C-Plus-Plus/projects/6#card-63413879
https://github.com/TheAlgorithms/C-Plus-Plus/projects/6#card-63413841
https://github.com/TheAlgorithms/C-Plus-Plus/projects/6#card-63413788

### Context

To keep our TODO list updated.

### Possible implementation

Remove the completed projects from the list.

**Comment by Panquesito7** [comment]
Updated. Thank you for reporting. 🙂
