### ISSUE TITLE
[FEATURE]Add an extremely rudimentary blockchain implementation in CPP

### ISSUE THREAD

**Issue by anuran-roy** [TheAlgorithms/C-Plus-Plus#1615]
### Detailed description

Can I add a program for a simple rudimentary simulation demo of a blockchain (minus the networking) in the Others folder, or do I add it to another folder?

### Context

I think a blockchain implementation in CPP will be nice, given how it's a statically typed language, and offers more fine-grained control than some dynamically typed language over the variables.

I think a simple implementation like this would help others to understand what goes on behind the scenes in a blockchain. I plan to use simple STL.

### Possible implementation

I intend to take a simple Object Oriented Approach. Since almost all programmers are acquainted with OOP concepts, it should be easier to understand for them.

**Comment by APathak666** [comment]
can I do it in C?

**Comment by APathak666** [comment]
> Yes, but in the C repository :)

I couldn't find anything related to blockchain in the C repo

**Comment by siriak** [comment]
You can be the first to add blockchain-related stuff there :)

**Comment by anuran-roy** [comment]
@siriak can you please assign someone to review my PR? Its number is #1644
