### ISSUE TITLE
[FEATURE] Codechef Beginner level problems

### ISSUE THREAD

**Issue by Sanika2103** [TheAlgorithms/C-Plus-Plus#1635]
### Detailed description

1. Visit  https://www.codechef.com/
2. Go to the practice and learn section
3. Go to Practice problems by difficulty level
  

### Context

Provide acceptable solutions for problems. It will help newbies to get the correct solution for a given problem statement.

**Comment by namangirdhar16** [comment]
@Sanika2103 i would like to work on this issue.

**Comment by akarshan2602** [comment]
@Sanika2103 hey, i would love to work on this issue and get it done asap, please assign it to me.


Regards,
Akarshan

**Comment by Denzil10** [comment]
Hey @Sanika2103  my rating has been between 2 and 3 star ( https://www.codechef.com/users/coda121)
I would be great for this as i am capable of writing short and beginner friendly comments explaining my code
I can give a good idea of the my approach, also the functions that i use would be basic so anyone case easily understand

**Comment by saquib678** [comment]
I want to work in this issue, @Sanika2103 Please assign it to me

**Comment by dhrubo28** [comment]
Hi, here's my work https://github.com/TheAlgorithms/C-Plus-Plus/pull/1933 for https://www.codechef.com/problems/CARDS777

**Comment by VIVEK-SUTHAR** [comment]
@I  Also Want To Contribute
