### ISSUE TITLE
[FEATURE]Addition of random forest algorithm

### ISSUE THREAD

**Issue by sonalee21** [TheAlgorithms/C-Plus-Plus#1658]
### Detailed description

Random forest is a flexible, easy to use machine learning algorithm that produces, even without hyper-parameter tuning, a great result most of the time. It is also one of the most used algorithms, because of its simplicity and diversity (it can be used for both classification and regression tasks).

### Context

As a data science and machine learning enthusiast, random forest algorithm is the most used algorithm in the field so everyone should know its basic.

### Possible implementation

Addition of random forest algorithm code with an example with explanation.

**Comment by sonalee21** [comment]
Please assign me this issue .

**Comment by Panquesito7** [comment]
Please don't ask to be assigned. See the [contributing guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#contributor).
If you want to help with this, feel free to submit a PR, and we'll review it.

Thank you. 🙂
