### ISSUE TITLE
[FEATURE]Add different variations of Segment Trees

### ISSUE THREAD

**Issue by shiladityab24** [TheAlgorithms/C-Plus-Plus#1671]
### Detailed description

Interval Trees(Segment Trees) is a heap-like data structure that can be used for making update/query operations upon array intervals in logarithmical time. I want to add different variations of segment trees like iterative segment tree, dynamic segment tree, segment tree with arithmetic progressions, and segment trees with Dijkstra along with the proper implementation of code.

### Context

A segment tree is a very useful data structure, used for range queries. It is a height-balanced binary tree with a static structure.
Some common applications of segment trees are used to find the sum of all elements in a range, find the min or max value of elements in a range, Update all elements in a range. Still, we can create more variations, this will give an idea about the proper application of segment trees, and also it will help to understand more in-depth about segment trees. The code of these algorithms will be written clearly and properly so that it should be easily understandable for all the users, especially for newcomers and beginners.

### Possible implementation

The variations of segment tree algorithms will be properly elaborated and the code will be implemented properly along with reasonable single line comments and multi-line comments.

**Comment by Panquesito7** [comment]
Feel free to make a PR to add that if you want! 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

I'll look forward to reviewing your PR as soon as I can. Let us know if you need any help here or in our [Discord server](https://discord.gg/c7MnfGFGa6). Thanks. 🙂

**Comment by KrishanKantAgnihotri** [comment]
I can add an Iterative Segment Tree. Please assign this to me.
