### ISSUE TITLE
[OTHER] Add Longest substring (without repeating characters) implementation

### ISSUE THREAD

**Issue by devjak26** [TheAlgorithms/C-Plus-Plus#1672]
### What would you like to share?

Longest substring without repeating characters

### Additional information

length of the longest substring without repeating characters. 
Important question - Asked in many company's interviews

**Comment by devjak26** [comment]
please assign me this issue

**Comment by pratham1103** [comment]
Yes I can, can u plz assign me this issue please

**Comment by Panquesito7** [comment]
Please do not ask to be assigned. Instead, make a PR and the maintainers will review it.
Just make sure that before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

I'll look forward to reviewing your PR. Thanks. 🙂

**Comment by Shiva336** [comment]
Is this issue still open?

**Comment by nishant-mahesh** [comment]
Hello! I have submitted my pull request for this issue. I hope my contribution is of value, and am looking forward for it to be reviewed!

**Comment by KaylaOates** [comment]
Hi! I'm submitting a poll request for this issue and plan to work on it soon

**Comment by rensaketh** [comment]
Hey, I submitted my pull request for this issue #1893

**Comment by tazyqui** [comment]
I have submitted my PR for this issue #1899

**Comment by rafaela-eacf** [comment]
Hello. I have submitted a pull request for this issue #1929. Thanks in advance for reviewing it.
