### ISSUE TITLE
In dynamic_programming folder Armstrong Number 

### ISSUE THREAD

**Issue by KrishanKantAgnihotri** [TheAlgorithms/C-Plus-Plus#1676]
### Description

The code in the Armstrong Number.cpp file is bugged it only works for 3 digit numbers perfectly.
https://en.wikipedia.org/wiki/Narcissistic_number
You can check the list of numbers here. 

### Expected behavior

defination of armstrong number is assumed wrong in implementation. For example 2 is Armstrong number but According to implementation it is not. 

### Actual behavior

for each digit power should be raised equal to n . where n is number of digits of a number.

### Steps to reproduce

one line of change is needed.

### Context

.

### Additional information
Pls assign this task to me.

**Comment by haarsh101** [comment]
Please assign it to me, I would like to fix the issue with Armstrong Number.cpp code.

**Comment by happy-t** [comment]
Fixed the bug, waiting for approval PR no. 1689,

Thanks.

**Comment by KrishanKantAgnihotri** [comment]
Hi everyone as this issue is raised by me I should have assigned this task isn't Why anyone else getting the change to create a PR before me?
