### ISSUE TITLE
[FEATURE]Articulation Point using Tarjan's Algorithm

### ISSUE THREAD

**Issue by krrahul23** [TheAlgorithms/C-Plus-Plus#1695]
### What would you like to share?

Tarjan Algorithm is used to check whether is graph is strongly connected or not
    it also find its uses to check the articulation points ,
    articulation points are those points whose removal increase in the number of connected components
    of graph , it also find its use in finding bridges , bridges are those edge whose removal increase in the
    number of connected components.

**Comment by Panquesito7** [comment]
For anyone that wants to contribute, please read the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass

I'll look forward to reviewing your PR. Thank you for your interest! 😄
