### ISSUE TITLE
[FEATURE]Add rot_13 cipher

### ISSUE THREAD

**Issue by pond-e** [TheAlgorithms/C-Plus-Plus#1696]
### Detailed description

Rot13 is a simple letter substitution cipher that replaces a letter with the 13th letter after it in the alphabet. ROT13 is a special case of the Caesar.

### Context

You will learn how to implement and learn about rot13.

**Comment by akarshan2602** [comment]
Hey! Can i work on this? I already made a code for Ceaser cypher, so i think i will be able to make this one too.


Regards,
Akarshan Kumar
