### ISSUE TITLE
[FEATURE] Binary Exponentiation

### ISSUE THREAD

**Issue by roeticvampire** [TheAlgorithms/C-Plus-Plus#1734]
### Detailed description

I'd like to add Binary Exponentiation under the Divide and Conquer directory.
The details for the algorithm can be found [here](https://cp-algorithms.com/algebra/binary-exp.html)

### Context

Currently, the repository does not have a lot many algorithms under Divide and Conquer, and binary exponentiation is a simple yet effective algorithm that displays the Divide and Conquer technique.

### Possible implementation

We use a recursive approach to calculate the exponent by checking if the last bit is on for our number and multiplying it with the square of the exponent of the power's half.

### Additional information

Assign it to me please.

**Comment by mgncodes** [comment]
Hi, I'd like to contribute to this issue. Kindly assign this to me. Thanks!

**Comment by Panquesito7** [comment]
> Hi, I'd like to contribute to this issue. Kindly assign this to me. Thanks!

Feel free to work on it! :)

**Comment by nishant-mahesh** [comment]
Hello! Is this issue still being worked on? If not, I'd be glad to work on implementing this :)

**Comment by fostersarah** [comment]
Hi, I would like to work on implementing this!
