### ISSUE TITLE
[BUG] Fix CodeQL warnings

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C-Plus-Plus#1826]
### Description

Currently, there are many CodeQL warnings. LGTM is marking our code quality as `B`. We need to get it higher (link: https://lgtm.com/projects/g/TheAlgorithms/C-Plus-Plus/alerts/?mode=list).

### Expected behavior

We should fix all the CodeQL/LGTM warnings.

### Actual behavior

LGTM is reporting 7 alerts, which marks our quality code as `B`.

### Possible fix

Fix all the CodeQL/LGTM warnings.

### Steps to reproduce

1. Go to https://lgtm.com/projects/g/TheAlgorithms/C-Plus-Plus/alerts/?mode=list.
2. You will see all the warnings CodeQL is reporting, which makes it easier for us to fix them.
3. There's a help button in case you need help or are confused with that error.

### Context

Having bugs in our code (even minimal bugs) can make it all go wrong or simply affect other students/people reading and understanding our algorithms.

### Additional information

Nope.

**Comment by 2kindsofcs** [comment]
Hello, I want to take this one.

**Comment by Panquesito7** [comment]
> Hello, I want to take this one.

Hey there! Feel free to make a PR and we'll review it! 😄

**Comment by ayushkedia05** [comment]
hello, i will handle this issue

**Comment by harsh628** [comment]
i want to help you in this...
