### ISSUE TITLE
Reversing a queue 

### ISSUE THREAD

**Issue by stutimohta20** [TheAlgorithms/C-Plus-Plus#1851]
### What would you like to share?

Reversing a queue using a stack in cpp language

**Comment by stutimohta20** [comment]
Please assign this to me

**Comment by webbdays** [comment]
Just swapping the start and end of queue is enough to reverse the queue.
I think using stack is unnecessary.
But still it's your wish.

**Comment by webbdays** [comment]
Yes.
Option 1:
When implementing the queue, add reverse method that swaps the start and end of the queue.

Option 2:
If using the std queue that is already implemented, then we can use stack.

**Comment by yashrajyash** [comment]
@Panquesito7 Please assign this issue to me.

**Comment by saquib678** [comment]
I want to work on this issue, Please assign this to me.

**Comment by sng125** [comment]
Hi! If this is still active, can I try working on this?

**Comment by Panquesito7** [comment]
Anyone of you, feel free to make a PR! Let us know if you need any help. 🙂

**Comment by alecrothenberg** [comment]
I just submitted a pull request for this issue, please let me know if I should make any changes to it!

**Comment by aryantalekar20** [comment]
I would like to work on this one if it is still open.

**Comment by EitanKog** [comment]
#1883 I created a reverse_queue file, please check it

**Comment by EitanKog** [comment]
#1883

**Comment by ngiridharan** [comment]
Hello! This was my first time contributing to open source, please take a look!
 #1887

**Comment by AvianTheFly** [comment]
> Anyone of you, feel free to make a PR! Let us know if you need any help. 🙂

Hi, can I please contribute to this project? It is for a school grade and I haven't had any responses.
