### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [TheAlgorithms/C-Plus-Plus#1866]
### Detailed description

Hii there, Greeting's of the day

I want to add new file to our repo :  TheAlgorithms /C-Plus-Plus/data_structures/   which is used to calculate the middle element of the singlly linkedlist . The name of the file can be MIddleElement_S.ll.cpp ( TheAlgorithms /C-Plus-Plus/ data_structures/MIddleElement_S.ll.cpp. 
I hope u find it useful . give acess to contribute this to ur repo . 
Thank u <3

 

### Context

As this file code is misssing int the data structure folder , so i think this is very important file  in the linked list  Data structure

**Comment by Panquesito7** [comment]
Hey there! Want to work on this? :)

**Comment by Vikash-8090-Yadav** [comment]
Yes , plss assign this to  me ..

**Comment by Xuewei-Chen** [comment]
Hi, is this issue still being worked on? If so, can I be assigned to this?

**Comment by Panquesito7** [comment]
> Hi, is this issue still being worked on? If so, can I be assigned to this as well?

There's a PR for it already #1867.

**Comment by Vikash-8090-Yadav** [comment]
Hii sir , greeting's!!

@Panquesito7 is there anything else I want to do with this code Or it's fine for merging ...?

:)

**Comment by Panquesito7** [comment]
> Hii sir , greeting's!!
> 
> @Panquesito7 is there anything else I want to do with this code Or it's fine for merging ...?
> 
> :)

I'll check it out, thanks. 🙂

**Comment by Vikash-8090-Yadav** [comment]
hey !! hope u r doing good ..... 
 @Panquesito7 ..any more chnages needed to this ..?
