### ISSUE TITLE
Print_linkedList.cpp

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [TheAlgorithms/C-Plus-Plus#1871]
### Detailed description

**Hey there , Greeting's of the day !! :smile: **
I want to contribute in your repo by adding  a new code file namely :   Print_linkedList.cpp and the respective repo path for this will be : **TheAlgorithms/C-Plus-Plus/data_structures/Print_linkedList.cpp**
<br>
Looking forward for your permission , assign this to me so that i can make pr properly with full documentation . 
Thank u :smile: 
Regard's 
Vikash 

### Context

This will print  all element of the singly linked list using loop .

**Comment by mishraabhinn** [comment]
Hi @Vikash-8090-Yadav what your code will do, will it be different from already implemented [LinkedList.cpp](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/data_structures/linked_list.cpp)

**Comment by Vikash-8090-Yadav** [comment]
Heyy there , 
Greeting's of the day ...
 Thanks for the comment !!

sorry for inconvenience , actually am not saw that code ..sorry 😓

**Comment by mishraabhinn** [comment]
> Heyy there , Greeting's of the day ... Thanks for the comment !!
> 
> sorry for inconvenience , actually am not saw that code ..sorry 😓

No problem. You can explore the repository and see how you can contribute. Cheers!
