### ISSUE TITLE
Incorrect Strassen Matrix Multiplication Algorithm.

### ISSUE THREAD

**Issue by amanmehara** [TheAlgorithms/C-Plus-Plus#195]
Currently it works only if **n** is 2.

**Comment by amanmehara** [comment]
https://github.com/TheAlgorithms/C-Plus-Plus/blob/a3ddfcdcf3c76d6380dffad37e6e2b80470a013e/Others/Strassen%20Matrix%20Multiplication.cpp#L27

**Comment by fhlasek** [comment]
this file no longer exists in the repo
