### ISSUE TITLE
[FEATURE]: Add Collision Detection Algorithms

### ISSUE THREAD

**Issue by LydianJay** [TheAlgorithms/C-Plus-Plus#1955]
### Detailed description

Add Collision Detection Algorithms.

### Context

AABB is a good start

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 😄👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.
