### ISSUE TITLE
License should be added.

### ISSUE THREAD

**Issue by LamdaLamdaLamda** [TheAlgorithms/C-Plus-Plus#199]
License including **LICENCE.md** should be added [Choose a licence](https://choosealicense.com/). 
 [TheAlgorithms/Python](https://github.com/TheAlgorithms/Python) selected the MIT variant.

**Comment by metablaster** [comment]
+1 here, I just made a few hittest mathematical functions and would like to contribute but realized that every single source file in the repository doesn't have a Copyright comment, and the repo is missing a license.

Definitely MIT would be normal choice.

**Comment by walter-ind** [comment]
Should I take up this issue? @yanglbme

**Comment by yanglbme** [comment]
yes @walter-ind

**Comment by walter-ind** [comment]
I have added the license. Please review my PR.
