### ISSUE TITLE
[FEATURE] Array Coding Question

### ISSUE THREAD

**Issue by Ayushi15-Vamne** [TheAlgorithms/C-Plus-Plus#1993]
### Detailed description

I found that array coding question's are missing in the repository. Since Array is very Important and essential topic in coding, so I want to contribute on that topic. 
Can I work on this issue?

### Context

Array is important in the world of programing and initial step to get into Competitive Coding.

### Possible implementation

I want to create one specific folder for Array Data Structure and will add important coding questions which will help in CP.

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 🎉
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

I'll review your PR as soon as I can.
If you need any help, let us know. Thank you. 😄

**Comment by modiniraj09** [comment]
I want to contribute to this repo?
please assign it to me..

**Comment by Ayushi15-Vamne** [comment]
Hey @modiniraj09/@Panquesito7,

I am working on it. I will let you know if I need any help.

Thanks!!

**Comment by Panquesito7** [comment]
> I want to contribute to this repo? please assign it to me..

Sorry, it seems Ayushi is already working on it.
You can take a look at other issues or look to make any improvements you think should be done. 🙂

Don't forget to join our [**Discord server**](https://the-algorithms.com)! 🙂

**Comment by Sanketh149** [comment]
I want to do this as a hacktoberfest contribution
Please assign this to me.

**Comment by Ayushi15-Vamne** [comment]
Hey @Sanketh149,
As I mentioned above also, I am already working on it and it almost ready.
I will let you know if I need any help.

Thanks!!

**Comment by harshdew02** [comment]
I think Matrix should be included in this folder, I have experience working on Array and Matrix so please assign me, I want to work on it.

**Comment by mishraabhinn** [comment]
> I think Matrix should be included in this folder, I have experience working on Array and Matrix so please assign me, I want to work on it.
Already assigned to @Ayushi15-Vamne
