### ISSUE TITLE
[FEATURE] Travelling Salesman - DP Optimisation using BitManipulation

### ISSUE THREAD

**Issue by Rytnix** [TheAlgorithms/C-Plus-Plus#1994]
### Detailed description

In this algo we are going to use Bitmasking technique to solve famous NP-hard Traveling Salesman Problem. 
As we know working with bits decreases the time complexity little bit.

### Context

The Time complexity  of naive approach is (n!)
where as the TC of  bitmask dp approach will be  (n^2 * 2^n) which is better than the naive approach.

### Possible implementation

For min. distance between two cells we are going to use BFS.
For the overall we are going to maintain a dp state  to track the visited houses and the last visited house to uniquely identify a state in this problem.
Therefore, we will be taking dp[index][mask] as our DP state.

### Additional information

This is one of the famous problem that is asked in competitive programming.

**Comment by Panquesito7** [comment]
Hey there! Feel free to work on this. Thank you! 🎉
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

I'll look forward to reviewing your PR. 🙂

**Comment by Aniket-debug** [comment]
can i take this issue?

**Comment by AyushAgrawal25** [comment]
Hi,

I would like to contribute, can you please assign this to me?

**Comment by mishraabhinn** [comment]
> Hi,
> 
> I would like to contribute, can you please assign this to me?

I think this is already taken.

**Comment by AyushAgrawal25** [comment]
> > Hi,
> > I would like to contribute, can you please assign this to me?
> 
> I think this is already taken.

No Issues

**Comment by Rytnix** [comment]
Addressed this feature through #2136.
