### ISSUE TITLE
[FEATURE] Add a games folder

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C-Plus-Plus#1997]
### Detailed description

Add a games folder including games such as Tic Tac Toe, memory game, and others.
P.S: there's already a games folder in the [C](https://github.com/TheAlgorithms/C/blob/master/games) repository.

### Context

This could attract more users to add their game implementations (as long as they follow our guidelines) if they don't have any algorithm.
However, it might not be the best option as this repository is mostly for DSA and not game implementations like the ones mentioned above.

### Additional information

Let me know what you think about this! Thank you. 🙂

**Comment by Rytnix** [comment]
Adding games folder would be a good idea.
Looking forward to implement this...

**Comment by Panquesito7** [comment]
Cool! Feel free to add the first game to the repository! 🎉 
Do let us know if you need any help here or on our [**Discord server**](https://the-algorithms.com/discord). 😄

**Comment by eshaanagarwal** [comment]
@Panquesito7 adding games would be interesting. Let me start with tic-tac-toe if its ok ?

**Comment by Panquesito7** [comment]
> @Panquesito7 adding games would be interesting. Let me start with tic-tac-toe if its ok ?

Sure! There's already a Tic Tac Toe game, but multiple implementations are always awesome. :)
Next time, there's no need to ask: just make a PR and we'll review it as soon as we can.

Thanks.
