### ISSUE TITLE
[FEATURE] Adding Best Time to Buy and Sell Stock series.

### ISSUE THREAD

**Issue by logic-404** [TheAlgorithms/C-Plus-Plus#2005]
### Detailed description

Best Time to Buy and Sell Stock is a very intuitive dynamic programming series that needs to be understood by any programmer trying to learn Data Structures and Algorithms. I hope for you to assign me this issue as I think it is important.

I am raising this issue as I want to make PRs for this repo as a part of my Hacktoberfest. Not only that, I want to be a frequent contributor to this repo as I have been doing DSA for quite a while now and I have upto 200 leetcode problems solved.
I hope you accept my issue

### Context

I feel like it is an important series of questions that are asked frequently in interviews. A good programmer that wants to be selected in a product based company must know these problems.

**Comment by rudrakshkarpe** [comment]
I can work on this issue, pretty much familiar with Best Time to Buy and sell stocks series from Leetcode!

**Comment by AjayMaheshwari23** [comment]
I have also done all questions of this series , assign me so that i can add solutions for them .

**Comment by gaurav-iitb** [comment]
plz assign me this issue I would like to code it in c++ with proper documentation

**Comment by rudrakshkarpe** [comment]
> plz assign me this issue I would like to code it in c++ with proper documentation

I am already working on it and about to raise a PR could you please look for some another issue?

**Comment by rudrakshkarpe** [comment]
I have raised a PR #2032 on this issue please check and let me know if any changes required
