### ISSUE TITLE
[inorder tree traversal]

### ISSUE THREAD

**Issue by shivani1706** [TheAlgorithms/C-Plus-Plus#2014]
### Detailed description

add a code for program of inorder tree traversal

### Context

it is important because without any traversal technique , we will not be able to traverse the tree.

**Comment by manish831** [comment]
@shivani1706 i want to do work on it, assign it to me!!

**Comment by mishraabhinn** [comment]
Guys please for the sake of hacktoberfest do not raise pr with irrelevant code.

**Comment by RiteshMohan186** [comment]
I would like to work on this issue please, also could you please add hacktoberfest label, thank you!

**Comment by Sanketh149** [comment]
I want to do this as a hacktoberfest contribution
Please assign this to me.

**Comment by amritgithub17** [comment]
I want to do this as a hacktoberfest contribution
Please assign this to me.

**Comment by yashvardhansingh15** [comment]
please assign this,  it could be my first contribution.

**Comment by Ivan2001otp** [comment]
I would like to contribute on this issue . Please assign this to me .

**Comment by Tushar2930** [comment]
Please Assign this to me. I want to contribute to this project

**Comment by Agniva144** [comment]
Sir , can you assign this to me?

**Comment by MayankPanda** [comment]
Can you assign this issue to me?

**Comment by SHWETA2JHA** [comment]
Please assign this task to me.

**Comment by mehtakevan** [comment]
hello sir,can you please assign this issue to me??
Thanks in advance :)
