### ISSUE TITLE
[FEATURE] Swap 2 numbers using Bit Manipulation

### ISSUE THREAD

**Issue by Mrjoy832** [TheAlgorithms/C-Plus-Plus#2016]
### Detailed description

Hey , I want to add detailed documentation , code  of **Swapping 2 numbers** using Bit Manipulation.
The Lanugauge I will use for solving this issue will be C++.

### Context

Its an important interview question that **Swap 2 numbers without using 3rd variable**, In that mostly guys answer using some staff like  doing some sort of addition , substraction but there if you answer with using Bit-manipulation then it will be eye catching and also better in case of Time complexity also .

### Possible implementation

I will use XOR operation to solve this question, and will be using C++

### Additional information

Please assign me ASAP...  I want to work on it.

**Comment by Mrjoy832** [comment]
@Panquesito7 Can you please assign this to me ?

**Comment by mishraabhinn** [comment]
Thanks for opening the issue. I have assigned it to you can raise a pr.

**Comment by kkartik07** [comment]
Can I also contribute here? Is someone still working on this?

**Comment by PuneetTri** [comment]
@Panquesito7 @mishraabhinn I have submitted a PR on this problem. I don't think @Mrjoy832 has successfully written his code yet. Can you please assign this issue to me, or just merge my PR? (I don't know how it goes, I'm still new to this). #2132 <- This is my PR for this issue.
