### ISSUE TITLE
[FEATURE] Find Only non-repeated element in a list using Bit Manipulation 

### ISSUE THREAD

**Issue by Mrjoy832** [TheAlgorithms/C-Plus-Plus#2018]
### Detailed description

Hey , I want to add detailed documentation , code of **finding only Non-repeating elements** using Bit Manipulation.
The Lanugauge I will use for solving this issue will be C++.

### Context

Its an important interview question that finding only Non-repeating elements in list, In that mostly guys answer using some O(n^2) loops , but there if you answer with using Bit-manipulation then it will be eye catching and also better in case of Time complexity also .

### Possible implementation

XOR operation will be used here

### Additional information

Please assign me ASAP... I want to work on it.

**Comment by Mrjoy832** [comment]
@mishraabhinn @Panquesito7  hello Sir,please assign this to me

**Comment by mishraabhinn** [comment]
Done @Mrjoy832

**Comment by kkartik07** [comment]
Can I contribute here by providing solution?

**Comment by Mrjoy832** [comment]
> Can I contribute here by providing solution?

Hey @kkartik07 I will be adding on this..please don't steal this issue from me buddy😢

**Comment by Gauri-AB** [comment]
Hii sir, pls assign this to me.

**Comment by mishraabhinn** [comment]
> Hello, Can you please assign this issue to me?
> 
> Thanks in advance :)

Aleready someone is working on this. Thanks for showing intrest in collaboration. Connect with us on discord and gitter. 
[Abhinn Mishra](https://twitter.com/mishra_abhinn)
