### ISSUE TITLE
[FEATURE] Adding STL documentation

### ISSUE THREAD

**Issue by narwar-veer** [TheAlgorithms/C-Plus-Plus#2041]
### Detailed description

I am capable of making a STL documentation for new user, with the help of this anyone can understand STL.

### Context

STL is quite difficult ot new user , so my documentation will help new user to understand it well.

**Comment by mishraabhinn** [comment]
Sound good.
Raise a pr with relevant work, it will be reviewed by some maintainer. Thanks.

**Comment by narwar-veer** [comment]
> Sound good. Raise a pr with relevant work, it will be reviewed by some maintainer. Thanks.

Sure I'll PR it soon..
