### ISSUE TITLE
Add Euler Tour code in graph section[FEATURE]

### ISSUE THREAD

**Issue by KritikaShrinivasan** [TheAlgorithms/C-Plus-Plus#2044]
### Detailed description

Adding the code with proper explaination for **euler tour of a tree** under the graph folder. 

### Context

This change will help new-comers to get familiarized with the concept of euler tour and the audience will be able to appreciate the importance of euler tour.

**Comment by mishraabhinn** [comment]
@kitty0804 Thanks for the raise of this issue. 
Please raise a pr with the relevant code. It will be reviewed thanks. 
Hope you have read the [Contributing Guildelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md)

**Comment by KritikaShrinivasan** [comment]
@mishraabhinn Hi, I have created a PR for this issue, kindly take a look : 
[https://github.com/TheAlgorithms/C-Plus-Plus/pull/2049](https://github.com/TheAlgorithms/C-Plus-Plus/pull/2049)

Thanks!

**Comment by KritikaShrinivasan** [comment]
@mishraabhinn Resolved all the issues, kindly let me know if any other changes are required. 
Thanks!

**Comment by KritikaShrinivasan** [comment]
@mishraabhinn Added test cases too, kindly review.
Thanks!
