### ISSUE TITLE
[FEATURE] Number of Islands using DFS algorithm

### ISSUE THREAD

**Issue by harshagrawal523** [TheAlgorithms/C-Plus-Plus#2048]
### Detailed description

Given an m x n 2D binary grid grid which represents a map of '1's (land) and '0's (water), return the number of islands.

An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically. You may assume all four edges of the grid are all surrounded by water.

### Context

This algorithm opens a wide variety of questions and this is basic need to other questions.

### Possible implementation

Using the DFS algorithm and traversing every possible islands to get the number of islands

**Comment by harshagrawal523** [comment]
@mishraabhinn Please review my [PR](https://github.com/TheAlgorithms/C-Plus-Plus/pull/2050#issue-1393667919) here

**Comment by thewpingmonk** [comment]
please assign this issue to me

**Comment by mishraabhinn** [comment]
> please assign this issue to me

Already taken by @harshagrawal523
