### ISSUE TITLE
[FEATURE] Distinct Number OF Islands Using DFS Algorithm

### ISSUE THREAD

**Issue by gaurav-iitb** [TheAlgorithms/C-Plus-Plus#2054]
### Detailed description

Given a boolean 2D matrix grid of size n * m. You have to find the number of distinct islands where a group of connected 1s (horizontally or vertically) forms an island. Two islands are considered to be distinct if and only if one island is not equal to another (not rotated or reflected).

### Context

This algorithm opens a wide variety of questions and this is basic need to other questions. This Question is the upgradation of the number of islands problem and is helpful in getting in-depth clarity 

### Possible implementation

Using the DFS algorithm and traversing every possible islands to get the number of islands

**Comment by harshagrawal523** [comment]
already done in [previous ](https://github.com/TheAlgorithms/C-Plus-Plus/issues/2048#issue-1393664614) issue

**Comment by gaurav-iitb** [comment]
@harshagrawal523  this is different question from that kindly read the desc properly

**Comment by gaurav-iitb** [comment]
@Panquesito7 please review my PR for this question

**Comment by thewpingmonk** [comment]
please assign this issue to me

**Comment by prabhatsingh985** [comment]
Please assign this task ,
I would really love to work at this

**Comment by PrakarshSingh5** [comment]
hi sir/madam 
can you please assign me i want to contribute

**Comment by Amisha2093** [comment]
Please, assign this problem to me.

**Comment by Masoom9587** [comment]
hello sir can you assign this issue to me i want to solve this issue.
