### ISSUE TITLE
2D sorted matrix search [enhancement]

### ISSUE THREAD

**Issue by aryanu027** [TheAlgorithms/C-Plus-Plus#2056]
### What would you like to share?

created an algorithm for sorted 2d matrix search in search section

**Comment by Brijesh-26** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by abhayanand08** [comment]
@aryanu027 @alkino @vbrazo @ericcurtin I want to contribute to this issue . Kindly assign this to me.

**Comment by ericcurtin** [comment]
I've only contributed to this repo once I think. Feel free to enhance things!

**Comment by deepalithakur17** [comment]
I can do it, may you please assign this to me

**Comment by Sounakray2003** [comment]
I would like to contribute

**Comment by ashutosh-kumar-kushwaha** [comment]
I want to work on this issue. Please assign this to me.

**Comment by drashan14** [comment]
Hello Sir/Mam,
I would like to contribute my knowledge in this issue , could you  assign me this issue.

**Comment by SourishJoshi8** [comment]
Hey,
I would like to work on this,
can u plz assign it to me

**Comment by Ankita3503** [comment]
Hello sir , please assign this issue to me.
