### ISSUE TITLE
Add Warshall's Transitive Closure Algorithm to Graph folder

### ISSUE THREAD

**Issue by abhilipsasahoo03** [TheAlgorithms/C-Plus-Plus#2063]
### Detailed description

Warshall's algorithm is used to determine the transitive closure of a directed graph or all paths in a directed graph by using the adjacency matrix. For this, it generates a sequence of n matrices. Where, n is used to describe the number of vertices.

### Context

In mathematics, the transitive closure of a binary relation R on a set X is the smallest relation on X that contains R and is transitive. In computer science, the concept of transitive closure can be thought of as constructing a data structure that makes it possible to answer reachability questions.  Warshall's algorithm can be implemented in both cases.

**Comment by abhilipsasahoo03** [comment]
I'd like to work on this issue!

**Comment by mishraabhinn** [comment]
> abhilipsasahoo03

Thanks for showing interest in contributing to the repository. 
Please raise a pr with the relevant code it will get reviewed.  
Before you start coding please read [Contribution Guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md)

**Comment by Sounakray2003** [comment]
I would like to work on this issue

**Comment by srusti610** [comment]
Hello sir,
I would like to contribute kindly assign me the issue.

**Comment by drashan14** [comment]
Hello Sir,
I would like to do this task could you assign me this task.
