### ISSUE TITLE
Broken link in C-Plus-Plus/CONTRIBUTING.md [OTHER]

### ISSUE THREAD

**Issue by mdfaizanahmed786** [TheAlgorithms/C-Plus-Plus#2064]
### Contributing
**Contributor**

1. [MIT License](https://github.com/TheAlgoritms/C-Plus-Plus/blob/master/LICENSE)

**Comment by Panquesito7** [comment]
Great catch! Would you like to work on this? 🙂

**Comment by mdfaizanahmed786** [comment]
Thank you! Shall I fix it and create a PR?

**Comment by Panquesito7** [comment]
> Thank you! Shall I fix it and create a PR?

Sure! Let us know if you need any help.

**Comment by mdfaizanahmed786** [comment]
I've fixed the link and created a PR. Please review it. Thank you for your time!

**Comment by mdfaizanahmed786** [comment]
> > Thank you! Shall I fix it and create a PR?
> 
> Sure! Let us know if you need any help.

> Hey there, can you label this PR as hacktoberest-accepted? Thank you!

**Comment by Panquesito7** [comment]
> > > Thank you! Shall I fix it and create a PR?
> > 
> > 
> > Sure! Let us know if you need any help.
> 
> > Hey there, can you label this PR as hacktoberest-accepted? Thank you!

Should be accepted automatically. This repository is participating in Hacktoberfest and the PR has been merged/approved. 🙂

**Comment by mdfaizanahmed786** [comment]
> > > > Thank you! Shall I fix it and create a PR?
> > > 
> > > 
> > > Sure! Let us know if you need any help.
> > 
> > 
> > > Hey there, can you label this PR as hacktoberest-accepted? Thank you!
> 
> Should be accepted automatically. This repository is participating in Hacktoberfest and the PR has been merged/approved. 🙂

Got it!
