### ISSUE TITLE
Add Activity Selector Greedy Algo

### ISSUE THREAD

**Issue by mehak-kalia** [TheAlgorithms/C-Plus-Plus#2068]
### What would you like to share?

I want to add activity selector greedy algorithm code in cpp

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

I'll look forward to reviewing your PR. 🙂

**Comment by Amisha2093** [comment]
Hey, is this issue, availed for contribution.
I would like to contribute to this problem.

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)

**Comment by PrakarshSingh5** [comment]
hi plz assign this to me

**Comment by Vaidehi-w** [comment]
can u assign it to me ?

**Comment by SwaggyRajput** [comment]
Hello sir, can u assign me this issue. I would love to grab this opportunity.
