### ISSUE TITLE
Keyword Cipher | C++ | Old cryptography techniques 

### ISSUE THREAD

**Issue by vipul-2003** [TheAlgorithms/C-Plus-Plus#2073]
hi there ,
I am Vipul Kumar Singh , Wanted to add code for `Keyword Cipher`  (old cryptography techniques ) under the [Cipher Folder](https://github.com/TheAlgorithms/C-Plus-Plus/tree/master/ciphers) .

**Please Assign this to me** @alkino @vbrazo @ericcurtin @AkarshSatija @gleisonbs

**Comment by ericcurtin** [comment]
I've only contributed to this repo once I think. Feel free to enhance things!

**Comment by vipul-2003** [comment]
i am going to make pull request on this ...
