### ISSUE TITLE
count_of_set_bits || C++. Can be solved using a single library to find the number of set bits in a number.

### ISSUE THREAD

**Issue by deoliaman00** [TheAlgorithms/C-Plus-Plus#2083]
### Detailed description

The current solution of the Problem counting no of set bits in a number is done with the traditional way that consumes more time complexity then the inbuilt library in C++ for counting the no of bits. So can I add that code too in the present code and improve it. 

### Context

The function  has O(k) time complexity which is way less then O(logn) since the k is no of set bits and n here is the number itself.

**Comment by deoliaman00** [comment]
I want to work on this issue immediately Kindly assign me this issue so that I can work on it asap. Thanks.

**Comment by mishraabhinn** [comment]
@deoliaman00 assigned. 
Please read the contribution guidelines before even starting to code. 
You can anytime raise pr and it will be reviewed. 
You can ping me or join the discord to get answers to any of your doubts. Thanks and happy coding.

**Comment by deoliaman00** [comment]
Please See my pull request as I have already done the work.

**Comment by thewpingmonk** [comment]
please assign this issue to me

**Comment by prabhatsingh985** [comment]
I would  love to work in this  project ;
 Please assign this to me

**Comment by nitink3006** [comment]
hello sir, would you please assign this issue to me..???
