### ISSUE TITLE
[BUG] Karatsuba's algorithm is not compiling

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C-Plus-Plus#2086]
### Description

If you try compiling [Karatsuba's algorithm](https://github.com/TheAlgorithms/C-Plus-Plus/tree/master/divide_and_conquer), it will crash with the Segmentation Fault error message.
I've tried various methods and things, but nothing has worked.

It seems the size is overflowing. This seems to be the problem: either the integer types are too small, or something else is wrong.

https://github.com/TheAlgorithms/C-Plus-Plus/blob/24f68ea4dbfda39f36a04864371ce706648383a4/divide_and_conquer/karatsuba_algorithm_for_fast_multiplication.cpp#L121-L126

### Expected behavior

The program should compile and pass the tests as excepted.

### Actual behavior

The program crashes with a Segmentation Fault error message.

### Steps to reproduce

1. Compile the program, either locally or using [Gitpod](https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus).
2. You will see the program fails with a Segmentation Fault error.
3. There's another minor `clang-tidy` error/warning that can be fixed by replacing all `int64_t` instances with `uint64_t`. That will give another overflow issue; something similar to this.

```bash
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 18446744073709551615) >= this->size() (which is 1)
Aborted
```

### Context

This is unprofessional. We should verify all of our implementations work fine.

### Additional information

If you've found a solution to this, feel free to submit a PR! Thank you. 🙂

**Comment by kunjgit** [comment]
can i work on this one??
