### ISSUE TITLE
[FEATURE] Machine_learning Model

### ISSUE THREAD

**Issue by narwar-veer** [TheAlgorithms/C-Plus-Plus#2088]
### Detailed description

I have made two Ml models ..
one on linear regression and
other on logistic regression and i want to contribute both of them ,
pls assign me the same ... 

### Context

It is coded with proper comments and heading new user can understand it well

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing! 🎉
Before submitting a PR, please ensure the following:

- The algorithm/implementation isn't a duplicate in this repository.
- Make your code per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
- Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by narwar-veer** [comment]
ya sure!

**Comment by Pana1v** [comment]
Hey, if this issue is still open, can you please assign it to me. I have two models ready.
