### ISSUE TITLE
[FEATURE] Adding detailed solution of Detect a negative cycle in a Graph problem

### ISSUE THREAD

**Issue by naksh2004** [TheAlgorithms/C-Plus-Plus#2091]
### Detailed description

We are given a directed graph. We need to compute whether the graph has a negative cycle or not. A negative cycle is one in which the overall sum of the cycle becomes negative.
Negative weights are found in various applications of graphs. For example, instead of paying cost for a path, we may get some advantage if we follow the path.

### Context

The idea is to use Bellman-Ford Algorithm which solves the problem in time complexity O(n*m) and space complexity: O(n)

### Possible implementation

Using Bellman-Ford Algorithm

**Comment by tiiitu** [comment]
Hi I would like to work on this, please assign me.

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)
