### ISSUE TITLE
Dijkstra's Algorithm

### ISSUE THREAD

**Issue by Kavita613** [TheAlgorithms/C-Plus-Plus#2119]
### What would you like to share?

Dijkstra Algorithm helps to find the shortest path in a graph.

I will provide the proper explanation and code for this algorithm.

**Comment by Kavita613** [comment]
Kindly assign this issue to me.

**Comment by ron0studios** [comment]
this has already been submitted I think, but I am not sure

**Comment by DxLRate** [comment]
do we have to describe Dijkstra's Algorithm?

**Comment by Panquesito7** [comment]
> this has already been submitted I think, but I am not sure

If I remember correctly, it has been added before in the repository.
However, there can be [multiple implementations](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#new-file-name-guidelines) of the same algorithm. 🙂

**Comment by naman5825** [comment]
hey I would like to contribute please assign me this issue.

**Comment by adarshtiwari40** [comment]
I will implement an optimized version of this code along with comments and other necessary details and explanation.

**Comment by srusti610** [comment]
Hello sir/madam,
I would like to contribute kindly assing me this issue.

**Comment by PrakarshSingh5** [comment]
hi sir/madam 
can you please  assign me

**Comment by drashan14** [comment]
I would like to solve this problem could you assign me this issue.

**Comment by Sreejavastar** [comment]
Hello, I would like to explain this particular problem in the best and simplest possible way, can you please assign this to me?
