### ISSUE TITLE
[FEATURE] Indexed priority queue

### ISSUE THREAD

**Issue by ron0studios** [TheAlgorithms/C-Plus-Plus#2160]
### Detailed description

I'd like to write an implementation for an indexed priority queue data structure for the project. 
It will be relatively simple, and mainly for educational purposes. 
I will write a class for an indexed priority queue that will be can hold any value type and a comparable type for the priority value. 
It will have the same time complexities of a regular priority queue, with the benefit of having access at O(1). 

The implementation will follow along the lines of william fiset's video tutorial:
https://youtu.be/jND_WJ8r7FE

### Context

A lot of graph algorithms that use priority queues to improve their time complexities, such as prim's algorithm and dijkstra. 

### Possible implementation

I have the code ready and will make a pull request after cleaning up and adhering to the project's code of conduct

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing! 🎉
Before submitting a PR, please ensure the following:

- The algorithm/implementation isn't a duplicate in this repository.
- Make your code per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
- Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by ron0studios** [comment]
Just made one, thanks!

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)

**Comment by PrakarshSingh5** [comment]
hi sir plz assign this work to me

**Comment by ron0studios** [comment]
> Hello, Can you please assign this issue to me? Thanks in advance :)

I'm already working on it, sorry

**Comment by PrakarshSingh5** [comment]
Ohk no problem
