### ISSUE TITLE
[OTHER] Trie implementation beginner

### ISSUE THREAD

**Issue by UltimateDip** [TheAlgorithms/C-Plus-Plus#2192]
### What would you like to share?

Currently in the repository existing Trie implementations are **not so beginner friendly**, So I want to contribute a beginner-friendly code **to implement** and also an example and **how to use this**.

**Comment by sarthakk1890** [comment]
Sir, I'ld like to handle this issue please assign it to me.

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)

**Comment by UltimateDip** [comment]
@Sakshi2002-Sinha  @sarthakk1890, Yeah sure, we can work together. 
@maintainers please assign this to us.
