### ISSUE TITLE
Josephus Problem general case

### ISSUE THREAD

**Issue by KunalKartik02** [TheAlgorithms/C-Plus-Plus#2198]
### Detailed description

I am proposing C++ implementation of the famous Josephus problem. The statement is as follows - Consider a game where there are n children (numbered 1,2,…,n) in a circle. During the game, every second child is removed from the circle, until there are no children left. In which order will the children be removed?

### Context

This is a very famous and standard problem in the world of competitive programming. This would help improve the mathematical and implementation skills of the programmer and enhance his/her thinking capabilities. It would help the programmer understand more of C++'s STL components. It would also come in handy in many coding rounds of various companies.

### Possible implementation

I am implementing it in C++. Data structure of set is being used to make searching easier and faster.

### Additional information

Kindly assign this issue to KunalKartik02 and kindly review my [https://github.com/TheAlgorithms/C-Plus-Plus/pull/2197](PR)

**Comment by KunalKartik02** [comment]
kindly review my [https://github.com/TheAlgorithms/C-Plus-Plus/pull/2197](PR)

**Comment by KunalKartik02** [comment]
PR*

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)

**Comment by Rishita0116** [comment]
Hello, I would like to work on this issue. Can you please assign it to me?

**Comment by Avdhesh-Varshney** [comment]
Hello, I would like to work on this issue. Can you please assign it to me?
