### ISSUE TITLE
[FEATURE] A exponent calculator for large values through binary exponentiation

### ISSUE THREAD

**Issue by srajansohani** [TheAlgorithms/C-Plus-Plus#2207]
### Detailed description

My contribution will make it easier and faster to calculate large exponents.

### Context

The pow function in STL has a return type of double and gives wrong values at large scale thus we an use binary exponentiation to avoid this miscalculation.

**Comment by srajansohani** [comment]
Please Assign this to me

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)

**Comment by Rishita0116** [comment]
Hello, I would like to work on this issue. Can you please assign it to me?

**Comment by Himanshukrabc** [comment]
Can you assign this to me?
