### ISSUE TITLE
[FEATURE] Add Kadane's Algorithm

### ISSUE THREAD

**Issue by Apocalyptic04** [TheAlgorithms/C-Plus-Plus#2209]
### Detailed description

Want to add Kadane's Algorithm to get largest sum of contiguous subarray.

### Context

Asked in many interviews. It is the most optimized solution to get largest sum of contiguous subarray.

Time Complexity: O(N)
Space Complexity: O(1)

**Comment by Apocalyptic04** [comment]
Will be happy if you assign me this issue and add hacktoberfest tag to it

**Comment by Anshul140** [comment]
I would also like to contribute solution to this problem in python.

**Comment by Jatin-parashar** [comment]
hey, assign this issue to me please

**Comment by shrutikahilale** [comment]
Please assign me, I have a good knowledge of DSA and I will make sure that I explain in the best possible way!

**Comment by pranavhole** [comment]
I would also like to contribute a solution to this problem. Please assign me this work

**Comment by Hiresh23** [comment]
i would like to contribute a solution to the problem i have a good knowlegde of DSA i feel i could help a lot

**Comment by Raghav0407** [comment]
I would like to contribute to this algorithm if you allow me please. This is my first time. Please assign me

**Comment by sajal-19** [comment]
Kindly assign this to me . I have an efficient solution for this.

**Comment by drashan14** [comment]
Hello Sir ,
I would like to contribute on this issue could you assign me this issue.

**Comment by drashan14** [comment]
Hello Sir ,
I would like to contribute on this issue could you assign me this issue.

**Comment by tripti1308** [comment]
Hello !!
kindly assing this to me .

**Comment by SHWETA2JHA** [comment]
I would like to contribute to the algorithm. Please assign this task to me.

**Comment by BugsBunny-PG** [comment]
Hello Maintainer,
I want to solve this problem ,please assign this issue to me.

**Comment by vikash-19** [comment]
Hello maintainer,
can you please assign this issue to me and hacktoberfest tag to it?

**Comment by UY24** [comment]
Hello,  I am happy to solve the issue for you, so can you please assign this issue to me and hacktoberfest tag to it?

**Comment by yashharne** [comment]
Hello Maintainer,
I would be more than happy to solve this problem and contribute to this algorithm.
Please assign this issue to me and hacktoberfest tag to it.

**Comment by prabhatsingh985** [comment]
Yes I would like to contribute..

**Comment by ishita126jain** [comment]
can you assign this issue to me

**Comment by Masoom9587** [comment]
can you assign this issue to me

**Comment by Sakshiwalode28** [comment]
I would like to contribute to the algorithm. Please assign this task to me.

**Comment by Ajitkumar-25** [comment]
I WOULD LIKE TO CONTRIBUTE TO THIS PROBLEM .PLEASE ASSIGN THIS TASK TO ME .

**Comment by Ankita3503** [comment]
Hello sir , I have a good knowledge of DSA so can you please assign this issue to me?
