### ISSUE TITLE
[FEATURE] Construct Binary Search Tree from Preorder Traversal

### ISSUE THREAD

**Issue by Amisha2093** [TheAlgorithms/C-Plus-Plus#2246]
### Construct Binary Search Tree from Preorder Traversal.

**Problem Statement:**
Given an array of integers preorder, which represents the preorder traversal of a BST (i.e., binary search tree), construct the tree and return its root.

**Test Case:**
Input: preorder = [8,5,1,7,10,12]
Output: [8,5,10,1,7,null,12]

### Context

This is a very famous and standard problem asked in most of the interviews. This will enhance the logical thinking of the programmer.

### Possible implementation

A binary search tree is a binary tree where for every node, any descendant of Node.left has a value strictly less than Node.val, and any descendant of Node.right has a value strictly greater than Node.val.

A preorder traversal of a binary tree displays the value of the node first, then traverses Node.left, then traverses Node.right.

**Comment by abhisek247767** [comment]
I would also like to contribute a solution to this problem.

**Comment by BugsBunny-PG** [comment]
Hello Maintainer,
I want to solve this problem ,please assign this issue to me.

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)

**Comment by PrakarshSingh5** [comment]
Hi sir/mam can you please assign this issue to me ,
i think i can do it very well

**Comment by Rishita0116** [comment]
Hello, I want to work on this issue and I have a good knowledge of DSA. Can you please assign it to me?

**Comment by ZohaiAli** [comment]
Hello sir!
I am already done with this issue please assign me so I can handover you the code

**Comment by Masoom9587** [comment]
hello sir can you assign this issue to me i want to solve this issue.

**Comment by Sakshiwalode28** [comment]
I would like to contribute to the algorithm. Please assign this task to me.
