### ISSUE TITLE
Adding algorithm for Tower of Hanoi Problem

### ISSUE THREAD

**Issue by MOUSAM-AGARWAL** [TheAlgorithms/C-Plus-Plus#2263]
### Detailed description

I want to add an algorithm for the problem of  "Tower of Hanoi" explaining the work flows of the algo , schematic representation , C++ code and all the required documentation.

### Context

This is an common Problem and it will be very useful for the beginners who want to understand different uses of stack and how it is useful in solving real world issues,

### Additional information

please assign this issue to me under the label of "Hacktoberfest 2022".

**Comment by UY24** [comment]
Hello, I am happy to solve the issue for you, so can you please assign this issue to me and hacktoberfest tag to it?

**Comment by ayushrathore111** [comment]
hello sir can you assign this isssue to me i want to solve this issue.

**Comment by RishabhRawatt** [comment]
hello sir i would like to work on that issue i have good knowledge of dsa and i will love to contribute in that issue

**Comment by Rishita0116** [comment]
Hello sir, I want to work on that issue. Can you please assign this to me?

**Comment by anushkag1203** [comment]
Hello sir , I'm really interested in solving this issue .I have a great repo of DSA. Can you plz assign this issue to me?

**Comment by Masoom9587** [comment]
hello sir can you assign this issue to me I want to solve this issue.

**Comment by DeepanshuRohilla15** [comment]
Hello sir, can you please assign this issue to me under the label of "Hacktoberfest 2022".

**Comment by drashan14** [comment]
Hello sir/mam
i would like to do this task could you assign me this task .

**Comment by rucha967** [comment]
I have already solved problems related to Hanoi Tower. Please assign me this task. I would complete this task.

**Comment by SwaggyRajput** [comment]
Hello sir, can u assign me this issue. I would love to grab this opportunity.
