### ISSUE TITLE
[OTHER] Update Discord links

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C-Plus-Plus#2274]
### What would you like to share?

We're using a new link for The Algorithms' Discord invitation.
All Discord invitation links should point to `https://the-algorithms.com/discord/`.

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners. 🙂

**Comment by kunjgit** [comment]
can i work on this??

**Comment by kunjgit** [comment]
can i work on this??

**Comment by kunjgit** [comment]
I have checked all the discord link is already pointing to this link only please can you clear me what is the issue??

**Comment by Panquesito7** [comment]
https://github.com/TheAlgorithms/C-Plus-Plus/search?q=c7MnfGFGa6
There are still a few instances that need to be updated.

**Comment by Sreejavastar** [comment]
Hello, as a first timer I would to start my contribution to open source from this issue , so can you please assign me this?

**Comment by Harsh-dhariwal** [comment]
hi,I'm working on this issue!!
