### ISSUE TITLE
boyer moore voting algorithm

### ISSUE THREAD

**Issue by navodayan14** [TheAlgorithms/C-Plus-Plus#2293]
### Detailed description

this algo is widely used to find majority elements in a array:

### Context

this algo is asked in many interviews.

**Comment by navodayan14** [comment]
please assign to me

**Comment by deepug12** [comment]
Hello Sir,
Please assign this task to me!

**Comment by Masoom9587** [comment]
hello sir can you assign this issue to me I want to solve this issue.

**Comment by SwaggyRajput** [comment]
Hello sir, can u assign me this issue. I would love to grab this opportunity.

**Comment by Sakshiwalode28** [comment]
I would like to contribute to the algorithm. Please assign this task to me.

**Comment by Himanshukrabc** [comment]
PLease assign this task to me. I would like to contribute.
