### ISSUE TITLE
i want to add circular queue implementation using array 

### ISSUE THREAD

**Issue by kunjgit** [TheAlgorithms/C-Plus-Plus#2301]
### Detailed description

it is extended version of circular queue that we use generally

### Context

it is important to know it because it can help you to utilize the space of array

**Comment by Nmn200** [comment]
hello Sir, can u assign this issue to me?

**Comment by ZohaiAli** [comment]
i am already done this code please assign me this task

**Comment by 26Saksham** [comment]
I want to add code ,could you assign me this task

**Comment by Masoom9587** [comment]
please assign it to me

**Comment by DeepanshuRohilla15** [comment]
Can i contribute to this program

**Comment by ZohaiAli** [comment]
i am already done this code please assign me this task

**Comment by SwaggyRajput** [comment]
Hello sir, can u assign me this issue. I would love to grab this opportunity.

**Comment by Sreejavastar** [comment]
Hello, I would like to contribute to this program, can you assign this to me?

**Comment by SUJ001** [comment]
Hello, can I be assigned for this. It would help me a lot as my first on github and I'm already done with the code.
