### ISSUE TITLE
[FEATURE] Count Set bits using Lookup Table

### ISSUE THREAD

**Issue by KartikeySharma** [TheAlgorithms/C-Plus-Plus#2310]
### Detailed description

This is an optimized approach to the classic O(log n) approach.
This one has O(1) where the lookup table will be generated at compile time.

### Context

Optimized Approach to Count Set bits

**Comment by KartikeySharma** [comment]
Pls assign this to me @mishraabhinn

**Comment by AMANSAINI7144** [comment]
can you please assign this to me I can solve it.

**Comment by AMANSAINI7144** [comment]
[countSetBit.cpp.txt](https://github.com/TheAlgorithms/C-Plus-Plus/files/9836893/countSetBit.cpp.txt)
