### ISSUE TITLE
Binary Exponentiation Implementation

### ISSUE THREAD

**Issue by codurr1** [TheAlgorithms/C-Plus-Plus#2323]
### Detailed description

Adding the best possible Binary Exponentiation Implementation with modulo

### Context

Better Implementation

**Comment by Raunik2** [comment]
Can u please assign me this task

**Comment by xakep8** [comment]
I have written the code for this
https://github.com/TheAlgorithms/C-Plus-Plus/pull/2345
this is the link to the pull request. Please tell me if any changes are required.
