### ISSUE TITLE
Naive Pattern Search

### ISSUE THREAD

**Issue by zafar-hussain** [TheAlgorithms/C-Plus-Plus#2330]
Detailed description

 Naive Pattern Search

     Searches for the given pattern in the provided text,
 
     parameters :
          pat :  Pattern to search for
          txt:    Text to search in
   
    returns 
          An integer,  position of the pattern if it exists, else a boolean false
 

### Context

Is commented in detail and includes tests also.

**Comment by SwaggyRajput** [comment]
Hello sir, can u assign me this issue. I would love to grab this opportunity.

**Comment by Himanshukrabc** [comment]
Could you please assign this to me?
