### ISSUE TITLE
N-Queens Problem

### ISSUE THREAD

**Issue by jpsxlr8** [TheAlgorithms/C-Plus-Plus#2342]
I would like to add the N-Queens problem to the repo.
```N queens problem is one of the most common examples of backtracking. Our goal is to arrange N queens on an NxN chessboard such that no queen can strike down any other queen. A queen can attack horizontally, vertically, or diagonally.```

Please assign me this task.

**Comment by JaiSukheja** [comment]
Hello, Please can you assign this to me

**Comment by SwaggyRajput** [comment]
Hello sir, can u assign me this issue. I would love to grab this opportunity.

**Comment by Purvi-sai** [comment]
I would like to contribute in this issue. Please assign this to me.

**Comment by Sakshiwalode28** [comment]
I would like to contribute to the issue. Please assign this task to me.

**Comment by krushnal57** [comment]
hello, sir i would like to solve this issue, i would like to solve the problem through a new my point of view.
can you assign this issue to me?

**Comment by vrinda01go** [comment]
Hey! I am interested in adding this problem and solving it through a beginner-friendly approach. Could you please assign me this?@jpsxlr8

**Comment by ShiveshSinghRao** [comment]
hey! I am interested in this problem as I have already solved this with two different approaches kindly assign this to me

**Comment by mohan792** [comment]
Hey, I have learned about N-Queens using Backtracking. I would really like to grab this opportunity and contribute. Please assign this task to me...
