### ISSUE TITLE
Reverse Word Wise

### ISSUE THREAD

**Issue by Jainsuhani2021** [TheAlgorithms/C-Plus-Plus#2360]
### Detailed description

input: Hacktober Fest
output: Fest Hacktober

### Context

this will help to reverse the sentence

**Comment by Jainsuhani2021** [comment]
Please assign this issue to me

**Comment by Jainsuhani2021** [comment]
https://github.com/TheAlgorithms/C-Plus-Plus/pull/2359#issue-1422321226
@aadarshkt
sir please have a look

**Comment by ShreyaGupta12** [comment]
Hello Sir, Please assign this issue to me.

**Comment by siddhant7701** [comment]
If you would assign me this issue I'd fix it.

**Comment by siddhant7701** [comment]
Will you please allow me to solve this issue.

**Comment by Ankita3503** [comment]
Hello sir , Please assign me this issue.
