### ISSUE TITLE
[OTHER] Move to FreeGlut 3.2.2?

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C-Plus-Plus#2398]
### What would you like to share?

I checked the releases and it seems it's a bugfix release, which should make things better for us and shouldn't break anything as well.
Should we update to FreeGlut 3.2.2 or stay in 3.2.1? We'd have to verify everything works as excepted.

https://github.com/FreeGLUTProject/freeglut/releases/tag/v3.2.2

**Comment by Panquesito7** [comment]
CC: @tjgurwara99.

**Comment by tjgurwara99** [comment]
Sure go ahead - I don't have any objections 😄
