### ISSUE TITLE
Add more algorithms

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/C-Plus-Plus#24]
This repo has less contributions. Please add more algorithms. 

See the structure and README of this repo for reference
https://github.com/TheAlgorithms/Python

**Comment by goyaljai** [comment]
i would like to contribute. thanks

**Comment by dynamitechetan** [comment]
@goyaljai  Sure. Thanks.

**Comment by goyaljai** [comment]
which type of algortihms? and where and how to add?

**Comment by joealam** [comment]
Is there any kind of contribution guide, or at least more information about the desired format of the contributions?

For example: should every algorithm be a single file? should they aim to be runnable without additional dependencies? etc.

**Comment by shivamgor498** [comment]
can we add cocktail sort algorithm??

**Comment by AnupKumarPanwar** [comment]
@joealam A single file is preferred and keep modular approach. Divide you code into function instead of breaking into multiple files and use the general head files for basic algorithms.

**Comment by Vehemos** [comment]
I would like to contribute to this. Thanks!

**Comment by vishvanath45** [comment]
I would like to contribute by adding Dijsktra Algorithm.

**Comment by shubhammatta** [comment]
I would like to add - Disjoint_Set_Union , Range_Minimum_query(Using Sparse Table) , KMP(Knuth–Morris–Pratt) Algorithm , Lowest_Common_Ancestor.

**Comment by VibhorCodecianGupta** [comment]
I'd like to add some sweet functions to Linked Lists and other algorithms like Count Sort, segmented sieve and totient functions. It'd be great if you acknowledged!

**Comment by arpanjain97** [comment]
I'd like to add the following shortest distance algorithms :  
1. Dijkstra
2. Bellman-Ford
3. Floyd-Warshall

**Comment by nghiaxlee** [comment]
Hello, I'd like to add Comb Sort algorithm

**Comment by rohitchugh9** [comment]
I would like to add Dynamic Programming Algorithms.
1. Edit Distance
2. 0/1 Knapsack
3. Egg Dropping Puzzle
4. Subset Sum
5. All Valid Parentheses

**Comment by rsenwar** [comment]
#138 Have a look at this PR, I am looking to add more programs related to Mathematics.

**Comment by GOVINDDIXIT** [comment]
I want to add optimal BST in DP category

**Comment by anudishjain** [comment]
Hi, I would like to add the following Dynamic Programming Algorithms,

- Trapping Rain Water (1D)
- Maximum Product Subarray
- Number of ways to decode a given number as a string (Decode Ways)

**Comment by shivansh2598** [comment]
Hi, I would like to add the following Algorithms,

1. Binomial Coefficient in the DP category.
2. Finding LCM using the Euclidean algorithm in the Math category.

**Comment by sankalpchauhan-me** [comment]
Hi, I would like to add the following Algorithm to Range Queries:
-> Binary Indexed Tree/Fenwik Tree

**Comment by tanaytoshniwal** [comment]
I would like to add Bit Masking / Bit Manipulation Algorithms
- Check ith bit
- Check Odd or Even
- Check Power of 2
- Clear all bits from MSB
- Convert Number to Binary
- Flip ith Bit
- Return First Set Bit
- Turn Off First Set Bit
- Turn Off ith bit
- Turn On ith bit

**Comment by Pratap2018** [comment]
I want to add a new searching algorithm.

**Comment by RitvijSrivastava** [comment]
#### Added Iterative Implementation of Quick Sort #343

**Comment by vishaldhull09** [comment]
i want to add algorithm to detect loop in a linked list.

**Comment by pinho** [comment]
I have implemented manually code for split a string.
I would like to add this algorithm here... 

* Split a string through a separator char

**Comment by atjustbeinghumaid** [comment]
I would like to contribute by adding solution to Maximum Size Sub-Square problem through Dynamic Programming

**Comment by ghostrider1234** [comment]
I would like to add Counting Sort Algorithm

**Comment by Xacrolyte** [comment]
Added a Bresenham Line Algorithm under the Graphics section. Adding more    
#478

**Comment by instinxt** [comment]
would like to add data structure programs for queue , linked list variations , if this issue is still open

**Comment by devbhansingh** [comment]
I would like to contribute to this project. Are there any particular algorithms that this project needs?

**Comment by kvedala** [comment]
You can contribute 
1. code that addresses open [issues](https://github.com/TheAlgorithms/C-Plus-Plus/issues)
2. code that is in line with the repo objectives in the [readme file](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/README.md)
3. Suggestions in the [projects](https://github.com/TheAlgorithms/C-Plus-Plus/projects)

Whatever you contribute, ensure to read the repo guidelines and checklist provided in the description when creating a pull-request. This is your checklist that you have not reviewed at all: https://github.com/TheAlgorithms/C-Plus-Plus/pull/1187#issue-497492333

**Comment by fhlasek** [comment]
@kvedala this issue seems like an anti-pattern type of issue with no particular way of resolving it. Let me close it and reopen if  you think there's a good reason to have it.
