### ISSUE TITLE
[OTHER] Add test, documentation according to the contribution format.

### ISSUE THREAD

**Issue by tapasrnk** [TheAlgorithms/C-Plus-Plus#2424]
### What would you like to share?

Currently some of the algorithms (i.e. [fibonacci_bottom_up.cpp](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/dynamic_programming/fibonacci_bottom_up.cpp)) don't have proper documentation and tests added as per the contribution guideline. Adding the tests would help to catch any bug before hand.

**Comment by tapasrnk** [comment]
PR : https://github.com/TheAlgorithms/C-Plus-Plus/pull/2425

**Comment by LeahKorol** [comment]
Hello, Can you please assign this issue to me?
