### ISSUE TITLE
[FEATURE] Add Box Stacking problem in Dynamic Programming

### ISSUE THREAD

**Issue by PrathamRa0** [TheAlgorithms/C-Plus-Plus#2443]
### Detailed description

Box Stacking problem is one of the most famous problems in Dynamic Programming and acts as a model questions to many problems out there. 

### Context

I was in a interview and faced this question regarding box stacking. I had to struggle to find the algorithm and ended messing up the interview. So I thought if it would be there along with other box stacking problems it would be helpful to one and all.

### Possible implementation

/* Dynamic Programming top-down implementation of Box Stacking problem */
#include <bits/stdc++.h>
using namespace std;

/* Representation of a box */
class Box {
    public:
	    int length;
	    int width;
	    int height;
};

// dp array
int dp[303];

int findMaxHeight(vector<Box>& boxes, int bottom_box_index, int index)
{

	// base case
	if (index < 0)
		return 0;

	if (dp[index] != -1)
		return dp[index];

	int maximumHeight = 0;

	// recurse
	for (int i = index; i >= 0; i--) {

		// if there is no bottom box
		if (bottom_box_index == -1 || (boxes[i].length < boxes[bottom_box_index].length && boxes[i].width
					< boxes[bottom_box_index].width))

			maximumHeight = max(maximumHeight,findMaxHeight(boxes, i, i - 1) + boxes[i].height);
	}

	return dp[index] = maximumHeight;
}

/* wrapper function for recursive calls which
Returns the height of the tallest stack that can be
formed with give type of boxes */
int maxStackHeight(int height[], int width[], int length[],int types)
{
	// creating a vector of type Box class
	vector<Box> boxes;

	// Initialize dp array with -1
	memset(dp, -1, sizeof(dp));

	Box box;

	/* Create an array of all rotations of given boxes
	For example, for a box {1, 2, 3}, we consider three
	instances{{1, 2, 3}, {2, 1, 3}, {3, 1, 2}} */
	for (int i = 0; i < types; i++) {

		// copy original box
		box.height = height[i];
		box.length = max(length[i], width[i]);
		box.width = min(length[i], width[i]);

		boxes.push_back(box);

		// First rotation of box
		box.height = width[i];
		box.length = max(length[i], height[i]);
		box.width = min(length[i], height[i]);

		boxes.push_back(box);

		// Second rotation of box
		box.height = length[i];
		box.length = max(width[i], height[i]);
		box.width = min(width[i], height[i]);

		boxes.push_back(box);
	}

	// sort by area in ascending order .. because we will be dealing with this vector in reverse
	sort(boxes.begin(), boxes.end(), [](Box b1, Box b2) {
		// if area of box1 < area of box2
		return (b1.length * b1.width) < (b2.length * b2.width);
	});

// Uncomment following two lines to print all rotations
	//for (int i = boxes.size() - 1; i >= 0; i-- )
// printf("%d x %d x %d\n", boxes[i].length, boxes[i].width, boxes[i].height);

	return findMaxHeight(boxes, -1, boxes.size() - 1);
}

int main()
{

	// where length, width and height of a particular box
	// are at ith index of the following arrays
	int length[] = { 4, 1, 4, 10 };
	int width[] = { 6, 2, 5, 12 };
	int height[] = { 7, 3, 6, 32 };

	int n = sizeof(length) / sizeof(length[0]);

	printf("The maximum possible height of stack is %d\n", maxStackHeight(height, length, width, n));

	return 0;
}

### Additional information

I have attached the code to it as well, if there is any issue in the syntax or the formatting of the code. Please let me know

**Comment by Panquesito7** [comment]
Great, thank you! 👍 Would you like to work on this?
If so, before submitting a PR, please ensure the following:

- The algorithm/implementation isn't duplicated in this repository.
- Make your code per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
- Ensure that all the [automated tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by realstealthninja** [comment]
There were two attempted implementation of this algorithm; #1516 and #2435 if anyone would like to implement this in the repo you could make these your references as both were closed. If you need any help you can let us know. 🙂 Good luck.

**Comment by Putul1519** [comment]
I wanted to work on this.

**Comment by realstealthninja** [comment]
If you want to just do

**Comment by PrathamRa0** [comment]
I will start working on this right away.
