### ISSUE TITLE
[FEATURE] 3D vector rotation via Rodrigues' formula

### ISSUE THREAD

**Issue by AlexAbrudan** [TheAlgorithms/C-Plus-Plus#2446]
### Detailed description

Add a new feature of vector rotation in 3D via Rodrigues' formula.

### Context

Instead of working with 3x3 rotation matrices, one could simply use Rodrigues' formula to compute the rotation of a vector by a given angle about a given axis more efficiently.

### Possible implementation

A simple implementation of Rodrigues' formula for the rotation of a vector about a given axis by a given angle.

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing! 🎉
Before submitting a PR, please ensure the following:

- The algorithm/implementation isn't duplicated in this repository.
- Make your code per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
- Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

Would you like to work on this? 🙂

**Comment by AlexAbrudan** [comment]
Yup, I'd love to!

**Comment by Putul1519** [comment]
I wanted to solve this issue.

**Comment by Panquesito7** [comment]
> Yup, I'd love to!

Hey there. Just checking in: are you still working on this? 🙂
