### ISSUE TITLE
[FEATURE] Update CMake to a newer version

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C-Plus-Plus#2479]
### Detailed description

It appears the version we're currently using is 3.9.0, which was released in [July 2017](https://cmake.org/pipermail/cmake/2017-July/065814.html).
I think it'd be great if we could update to a newer (or the latest) version, to have more security fixes, features, and as well as being up-to-date and ensure our project works with the latest versions.

### Context

This will ensure we have the latest security fixes and features, and make sure our project works with the latest versions of CMake.

### Possible implementation

Upgrade CMake to a newer or the latest version (the current version is 3.9.0).

**Comment by heysujal** [comment]
I'd like to work on this issue

**Comment by rbevin777** [comment]
PR made here: https://github.com/TheAlgorithms/C-Plus-Plus/pull/2505
