### ISSUE TITLE
[OTHER] documentation of namespaces contains phrases like `for IO operations`

### ISSUE THREAD

**Issue by vil02** [TheAlgorithms/C-Plus-Plus#2493]
### What would you like to share?

The documentation of some of the namespaces contain phrases like `for IO operations` or `for assert`.
![namespaces_main](https://github.com/TheAlgorithms/C-Plus-Plus/assets/65706193/c73bef26-47bc-4282-9d2d-9ab640b4bcf6)

### Additional information

I would suggest to replace `///` with `//` in the _motivation, why certain header was included_, e.g. change
```cpp
#include <cassert>  /// for assert
#include <string>   /// for std::string
#include <vector>   /// for std::vector
```
to
```cpp
#include <cassert>  // for assert
#include <string>   // for std::string
#include <vector>   // for std::vector
```

After such change, the documentation looks as follows:

![namespaces_fix](https://github.com/TheAlgorithms/C-Plus-Plus/assets/65706193/7bb440cc-77ae-47de-adca-bf82643062b0)

I already made it in vil02/C-Plus-Plus/fix_namespaces_docs@c25eea989947679398e40859a2d8a39757fd8426. Since this commit influences most of the `cpp` files, I also formatted all of them using `clang-format` (cf. vil02/C-Plus-Plus/fix_namespaces_docs@64571a1f0e9fceda0bf0bd9e65c6bb1d66deab42).

Please notice, that since all of the files are changed, the `Awesome CI Workflow` fails at `Lint modified files` step.

If you think that the above suggestion is the _way to go_, please let me know and I will make a suitable PR.

**Comment by realstealthninja** [comment]
well i checked out other name spaces in the same vain
i don't think the issue is the triple backslash it has something to do with the detailed description of each file.
looking further into it i found parts of the @details tag also present in the description of the namespace
if we do what you suggest. we'll have to remove @details tag @author tag ect.. 
https://thealgorithms.github.io/C-Plus-Plus/df/dce/namespacegraph.html#details

**Comment by vil02** [comment]
My conjecture is that comments starting with `//` are ignored by doxygen. The above example seems to confirm that.

I think issue you have mentioned comes from the fact that the documentation block of the problematic file is missing the `\file` tag - can you confirm that?

Since namespaces can span across multiple files documenting them is hard - the documentation of a given namespace should be only in one place (and contain the `\namespace` tag).

**Comment by Panquesito7** [comment]
If using `//` removes those problems, we should stick to that and replace that in all the current algorithms.
However, we must verify that's the real problem. What were the algorithms you checked?

**Comment by vil02** [comment]
> What were the algorithms you checked?
@Panquesito7 what do you mean by _algorithms_?

The problem occurs in several namespaces, e.g.:
- [`backtracking`](https://thealgorithms.github.io/C-Plus-Plus/db/dc0/namespacebacktracking.html#details),
- [`bit_manipulation`](https://thealgorithms.github.io/C-Plus-Plus/d7/d81/namespacebit__manipulation.html#details),
- [`ciphers`](https://thealgorithms.github.io/C-Plus-Plus/d6/d4e/namespaceciphers.html#details),
- ...

Should I take action as described above (the mentioned branch is slightly out of date - I will update it)?
