### ISSUE TITLE
Creating a directory for categorywise cpp code questions.[FEATURE]

### ISSUE THREAD

**Issue by swarajmhatre** [TheAlgorithms/C-Plus-Plus#2494]
### Detailed description

Hello. I was suggesting that this repository can have a directory where we can include CPP codes which will cover logic building concepts problems for using CPP. Like problems on numbers, strings, arrays, integers, pattern printing etc. 

### Context

I have around 200-250 questions solved covering the questions I have mentioned above. I was willing to contribute my code.

### Possible implementation

We can have a separate directory for this issue and inside we can have directories for different categories of problems.

**Comment by realstealthninja** [comment]
do you mean like a leet code directory? or just general algorithms? in which case you should try to fit your algorithms to the pre existing directories

**Comment by swarajmhatre** [comment]
I have some general algorithms. But also a lot of practice code of my own covering topics like loops, arrays, pointers, Pattern printing and all.

**Comment by realstealthninja** [comment]
I am not sure if that's too general for this repository. I think we are looking at more of problem solving type algorithms.
there are linked lists and binary tree traversal in one of the sub directories if that's what you mean. I'm sure one of the other maintainers knows more about this issue! thank for you for raising this one!

**Comment by Panquesito7** [comment]
Created a discussion about this on the Discord community. Let's see what others think.
I personally think it'd be great as many people will learn from that, but I'm not sure it 100% fits this repository.

**Comment by swarajmhatre** [comment]
Can you add me to the discord please?

**Comment by realstealthninja** [comment]
> Can you add me to the discord please?

we have a discord server! 
https://the-algorithms.com/discord
