### ISSUE TITLE
 Fibonacci numbers

### ISSUE THREAD

**Issue by naveenyadav15** [TheAlgorithms/C-Plus-Plus#25]
It is giving wrong answer.

**Comment by sachinarora707** [comment]
Hi @naveenyadav15 Can you be more specific with the issue?? It's working fine for me and giving a correct output. Fibonacci sequence is defined in 2 ways. One starts with 0 and 1. Other starts with 1 and 1. 
Both these sequences are correct. If this resolves the issue, please check.

**Comment by naveenyadav15** [comment]
Like, if your input is 50 it is giving wrong answer(negative)

**Comment by sachinarora707** [comment]
@naveenyadav15 i checked the code again. The problem is that the number at 48 is greater than the upper limit of a signed int, i.e., 2,147,483,647. So, the code breaks at the input greater than 47.

**Comment by naveenyadav15** [comment]
Okay, then we can correct it by using long long.

**Comment by Balance-Breaker** [comment]
For larger number we can implement it with different data structure so that there would be no problem with size of data-type. @sachinarora707  if required I can work on that.

**Comment by sachinarora707** [comment]
@naveenyadav15 Using unsigned long long int would improve it. But, it would still not work for very big numbers. For higher inputs, the code will break again.

**Comment by sachinarora707** [comment]
@Balance-Breaker Sure, work on the issue.

**Comment by christianbender** [comment]
I fixed the issue. I changed the datatype from **int** to **long long**.
This datatype can be overflow, too. But we increase the max limit.
