### ISSUE TITLE
[BUG] Wrong contributing link

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C-Plus-Plus#2502]
### Description

The PR template provides a link to the contributing guidelines.
However, that link is broken and must be fixed ASAP.

_Steps to contribute_

1. Fork the repository [here](https://github.com/TheAlgorithms/C-Plus-Plus/fork).
2. Create a new branch named `fix_contributing_link`.
3. Open the `.github/pull_request_template.md` file.
4. There's an HTML comment on the top of the file. Update the contributing file link to `https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md`.
5. Commit and push your changes.
6. Create a [pull request](https://github.com/TheAlgorithms/C-Plus-Plus/compare) to compare your changes.
7. You're done now! 🎉 You have to wait until the maintainers check your PR.

Let us know if you need any help! 🙂

### Expected behavior

The link should point to the contributing guidelines

### Actual behavior

The link points to a 404 page.

### Context

This should be fixed ASAP, as those who go to the link will receive a 404 page and might be confused or lost.

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners.

**Comment by abhisheksharma886** [comment]
Hello, I would like to work on this, can it be assigned to me

**Comment by Panquesito7** [comment]
Looks like #2503 was closed. I believe another PR can be created now.
CC: @anuragdaksh7, did you have any problems with the PR?
