### ISSUE TITLE
[FEATURE] Add self-tests in `greedy_algorithms/kruskals_minimum_spanning_tree.cpp`

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C-Plus-Plus#2509]
### Detailed description

The algorithm was documented in #2482, however, it is still missing self-test implementations that make sure the algorithm works as expected, which will make the algorithm fully up to our guidelines.

### Context

This is very much needed as without self-tests, it cannot be proved whether the algorithm gives the correct output.

**Comment by sOR-o** [comment]
i have code ready with all the required changes. can you assign it to me.

**Comment by avnis838** [comment]
Yes I would like to contribute to this issue along with adding code for the algorithm in very documented way. Please assign it to me.

**Comment by realstealthninja** [comment]
@sOR-o  can you give an update on this?

**Comment by avnis838** [comment]
Ya i have done but, my mid semester are near so i will be free from 28 of
Nov.

**Comment by avnis838** [comment]
I have some more to add, that i will then.

**Comment by Meetmendapara09** [comment]
Hi @reviewer,

I have implemented the solution for adding self-tests in greedy_algorithms/kruskals_minimum_spanning_tree.cpp as discussed in issue #2509. The pull request (#2707) includes all the necessary changes and has been tested to ensure it meets the requirements.

Please review the changes and let me know if there are any adjustments needed. If everything looks good, could you please merge this pull request?

Thank you!

**Comment by realstealthninja** [comment]
> I have implemented the solution for adding self-tests in greedy_algorithms/kruskals_minimum_spanning_tree.cpp as discussed in issue #2509. The pull request (#2707) 

No, there are no tests in that pull request
You refactored the code

**Comment by realstealthninja** [comment]
This is available for anyone whose interested!

**Comment by Monalisa0311** [comment]
I am interested in this. Is this issue still available? If so, I have the code ready with all the required changes. can you assign it to me?

**Comment by realstealthninja** [comment]
closed by #2727
