### ISSUE TITLE
Aho-Corasick pattern matching

### ISSUE THREAD

**Issue by egberts** [TheAlgorithms/C-Plus-Plus#2520]
### Detailed description

How about an Aho-Corasick algorithm?

### Context

It is about O(1) searching.

### Additional information

aho-corasick - https://en.m.wikipedia.org/wiki/Aho%E2%80%93Corasick_algorithm

**Comment by realstealthninja** [comment]
will you be implementing this?

**Comment by Saket009** [comment]
can you please assign this issue to me ? and mark file location

**Comment by Krishna-rudraksh70** [comment]
Hi,
I'm new to Hacktoberfest and I'm looking for a good first issue to contribute to. I noticed an issue in your repository regarding the "Aho-Corasick algorithm," which I've studied during my DSA course. I would like to request the opportunity to work on this issue.

I want to assure you that I will implement it in a time complexity of O(String_Size + Pattern_Size), and if I'm unable to achieve this in O(1).

**Comment by Aniket3063** [comment]
hi,
I wanna contribute to this repository. can you please assign this issue to me ?

**Comment by Monachaudhary** [comment]
I would like to work on this issue. Kindly assign it to me

**Comment by aniketmdinde** [comment]
Can you please assign this issue to me. I can successfully complete it.

**Comment by sarvo123** [comment]
hii , hoping you are doing well .
i am an enthusiast of data structure and algorithm . it's always fascinating the implementation and working of any algorithm .
i have a good command on dsa and i solved a lot of questions of dsa .
so "I'm interested in working on this Aho-Corasick algorithm issue. Is it possible to assign it to me, or could you guide me on how to get started?"

**Comment by muffinboy19** [comment]
can you please assgin this issue to me . I can complete it

**Comment by Taruns123** [comment]
Hi , I haved worked with Aho-Corasick algo and other pattern matching algorithms and would like to contribute to this issue. I am new to the world of open source contribution but have a decent knowledge of algorithms since I have been doing competitive programming since years. You may take  a look at my coding profiles listed on my page. And I would be glad to contribute to this community of algorithms.

**Comment by codetechie-abhay** [comment]
# Aho-Corasick Algorithm in C++

## Introduction

The Aho-Corasick algorithm is a string matching algorithm used for efficiently searching for multiple keywords in a given text. It operates with a time complexity of O(n + m + z), making it a powerful tool for text processing and pattern matching tasks.

This repository contains a C++ implementation of the Aho-Corasick algorithm.

## Features

- Efficient string searching for multiple keywords.
- Aho-Corasick algorithm implementation in C++.
- Easy-to-use interface for adding keywords and searching for matches.

# Aho-Corasick Algorithm in C++ - Algorithm Explanation

The Aho-Corasick algorithm efficiently searches for multiple keywords in a given text. Here's a step-by-step explanation of how the algorithm works, along with how it's implemented in the provided C++ code:

## Algorithm Explanation

1. **Keyword Addition**: 

   - Keywords, such as "apple," "banana," and "cherry," are added to a keyword trie data structure.

2. **Failure Link Construction**:

   - The algorithm constructs failure links between nodes in the keyword trie to efficiently navigate to the next potential match if a mismatch occurs while searching.

   - For each node, the algorithm determines the next node to visit in case of a mismatch by following the failure link, which ensures that no potential match is missed.

3. **Text Searching**:

   - During text searching, the algorithm processes each character in the input text.

   - It uses the constructed failure links to efficiently traverse the keyword trie while looking for keyword matches.

   - When a keyword match is found, the algorithm increments a counter associated with that keyword.

   - After processing the entire text, the algorithm provides a count of how many times each keyword was found in the text.

## Code Implementation - by Abhay Nauityal 



1. **Keyword Addition**:

   - Use the `addKeyword` method to add keywords to the Aho-Corasick structure.

2. **Failure Link Construction**:

   - Call the `buildFailureLinks` method to construct failure links between nodes in the keyword trie.

3. **Text Searching**:

   - Input text is processed using the `search` method, which returns a vector with counts of keyword matches.

4. **Displaying Results**:

   - The code prints out the keywords that were found in the text and the number of times each keyword was found.


please give me this opportunity

**Comment by 5ku11Cru5h3r** [comment]
I would really like to work on this file I have some code written and ready to be implemented. Please assign me the role

**Comment by egberts** [comment]
> # Aho-Corasick Algorithm in C++
> 
> 
> 
> ## Introduction
> 
> 
> 
> The Aho-Corasick algorithm is a string matching algorithm used for efficiently searching for multiple keywords in a given text. It operates with a time complexity of O(n + m + z), making it a powerful tool for text processing and pattern matching tasks.
> 
> 
> 
> This repository contains a C++ implementation of the Aho-Corasick algorithm.
> 
> 
> 
> ## Features
> 
> 
> 
> - Efficient string searching for multiple keywords.
> 
> - Aho-Corasick algorithm implementation in C++.
> 
> - Easy-to-use interface for adding keywords and searching for matches.
> 
> 
> 
> # Aho-Corasick Algorithm in C++ - Algorithm Explanation
> 
> 
> 
> The Aho-Corasick algorithm efficiently searches for multiple keywords in a given text. Here's a step-by-step explanation of how the algorithm works, along with how it's implemented in the provided C++ code:
> 
> 
> 
> ## Algorithm Explanation
> 
> 
> 
> 1. **Keyword Addition**: 
> 
> 
> 
>    - Keywords, such as "apple," "banana," and "cherry," are added to a keyword trie data structure.
> 
> 
> 
> 2. **Failure Link Construction**:
> 
> 
> 
>    - The algorithm constructs failure links between nodes in the keyword trie to efficiently navigate to the next potential match if a mismatch occurs while searching.
> 
> 
> 
>    - For each node, the algorithm determines the next node to visit in case of a mismatch by following the failure link, which ensures that no potential match is missed.
> 
> 
> 
> 3. **Text Searching**:
> 
> 
> 
>    - During text searching, the algorithm processes each character in the input text.
> 
> 
> 
>    - It uses the constructed failure links to efficiently traverse the keyword trie while looking for keyword matches.
> 
> 
> 
>    - When a keyword match is found, the algorithm increments a counter associated with that keyword.
> 
> 
> 
>    - After processing the entire text, the algorithm provides a count of how many times each keyword was found in the text.
> 
> 
> 
> ## Code Implementation - by Abhay Nauityal 
> 
> 
> 
> 
> 
> 
> 
> 1. **Keyword Addition**:
> 
> 
> 
>    - Use the `addKeyword` method to add keywords to the Aho-Corasick structure.
> 
> 
> 
> 2. **Failure Link Construction**:
> 
> 
> 
>    - Call the `buildFailureLinks` method to construct failure links between nodes in the keyword trie.
> 
> 
> 
> 3. **Text Searching**:
> 
> 
> 
>    - Input text is processed using the `search` method, which returns a vector with counts of keyword matches.
> 
> 
> 
> 4. **Displaying Results**:
> 
> 
> 
>    - The code prints out the keywords that were found in the text and the number of times each keyword was found.
> 
> 
> 
> 
> 
> please give me this opportunity
> 
> 
> 
> 
> 
> 

What about dynamically doing addKeyword in-situ?

Callback support at last matched character?

Return string matched?

**Comment by arsh-kamal** [comment]
hii i can work on this can you assign this to me

**Comment by omkarrk1010** [comment]
Hi! 👋

I am interested in contributing to this issue and would like to work on improving the Aho-Corasick algorithm implementation.  

I plan to:
- Add missing test cases for multiple and overlapping patterns
- Improve code readability and add comments/documentation
- Optional: Optimize memory usage and runtime efficiency

Please let me know if I can take this issue.  
Thanks!
