### ISSUE TITLE
[FEATURE] Articulation Point and Bridge for graphs.

### ISSUE THREAD

**Issue by Prabhat-Kumar-42** [TheAlgorithms/C-Plus-Plus#2561]
### Detailed description

What would you like to Propose?
Adding Code for finding Articulation Points and Bridges.

Problem Statement :

Given an adjacency list of a graph with vertices = v, having
0 based indexing. Find all Articulation Points and Articulation
Bridge Present in Graph.

Applications :

1. Network Flow
2. Used in map/city-path related computer programs

### Context

Articulation Point : vertex whcih when removed increases the number of
connected component in graph.

Articulation Bridge : edge which when removed increases the number of
connected component in graph.

eg : Given graph with vertices = 5 and
adj list is : vertex -> neighbours (Assuming all edges are bidirectional)
0 -> 1, 2
1 -> 2
2 -> 3
3 -> 4

   Graph is :

             0-------1
             |      /
             |     /
             |    /
             |   /
             |  /       4
             | /        |
             |/         |
             2----------3
  
      current connected component = 1

-> Articulation Points : 2 , 3
Explanation :

          -> When removing 2, graph changes to below and connected components increases
             from 1 to 2.

             0-------1
             |      /
             |     /
             |    /
             |   /
             |  /       4  
             | /        |
             |/         |
                        3

           -> When removing 3, graph changes to below and connected components increases
             from 1 to 2.

             0-------1
             |      /
             |     /
             |    /
             |   /
             |  /       4
             | /
             |/
             2
-> Articulation Bridges: edge : 2-3, edge: 3-4
Explanation :

          -> When removing edge : 2-3, graph changes to below and connected components increases
             from 1 to 2.

             0-------1
             |      /
             |     /
             |    /
             |   /
             |  /       4
             | /        |
             |/         |
             2          3

           -> When removing edge : 3-4, graph changes to below and connected components increases
             from 1 to 2.

             0-------1
             |      /
             |     /
             |    /
             |   /
             |  /       4
             | /
             |/
             2----------3

**Comment by Prabhat-Kumar-42** [comment]
Hey,
I have implemented it and submitted PR regarding it.
Please review it.
It is tested and works with all the test cases, but if any issues are found, please do let me know,
I will work on them asap.
Hope this helps the community.
Thank You !! :)

**Comment by DevAbhinay789** [comment]
@Prabhat-Kumar-42 Please assign me this project.I will complete this project as soon as possible using comments,appropriate variable names,explanation,image and in most efficient way.Greatly looking ahead to work with you.

**Comment by ABHIS2607** [comment]
@Prabhat-Kumar-42  can you assign me this i will work on it

**Comment by Prabhat-Kumar-42** [comment]
Hey @ABHIS2607 ,

I guess only maintainers can assign the issues. 

Now about this one, I have already implemented it and now waiting for the PR review from the maintainers.
