### ISSUE TITLE
[FEATURE] Bisection method

### ISSUE THREAD

**Issue by akhil-maker** [TheAlgorithms/C-Plus-Plus#2579]
### Detailed description

Add a bisection method in math folder

### Context

This method can help people to get code for bisection so as to get a root for any function in an interval

### Possible implementation

Add a program file

**Comment by MrImmortal09** [comment]
I'd love to add this. Can u pls assign-me.

**Comment by MrImmortal09** [comment]
Hi @akhil-maker , I'd love to add this. Can u pls assign-me

**Comment by kushchoudhary98** [comment]
@akhil-maker will you please add the "hacktoberfest-accepted" label

**Comment by CrypticRevenger** [comment]
Please assign me, I want to do it.

**Comment by dishhaa03** [comment]
https://github.com/dishhaa03/C-Plus-Plus/commit/f306f7f50eabfa5f646ccab18bb2a8ca3a48ccd7

I made a pull request, but something went wrong, it isn't showing the no. "#2579".
But I remember adding it.

**Comment by anasadh** [comment]
@kushchoudhary98 Can you please assign me this issue?
 I want to contribute in it.

**Comment by ABHIS2607** [comment]
@akhil-maker assign me the task

**Comment by NitishPal2013** [comment]
@akhil-maker , The bisection method is part of numerical methods. Some contributors have already implemented it into numerical_methods directory. I would suggest to remove this from the issues.
