### ISSUE TITLE
want to add Bankers algorithm

### ISSUE THREAD

**Issue by silky-modi22** [TheAlgorithms/C-Plus-Plus#2591]
### Detailed description

I want to add bankers algorithm in C++

### Context

The bankers algorithm is an important algorithm for deadlock avoidance

### Additional information

please assign me this issue under hactoberfest 2023. I want to work on this issue

**Comment by Tulsi5990** [comment]
I want to work on this issue.

**Comment by AniketShirou** [comment]
Please assign this issue to me
