### ISSUE TITLE
[FEATURE] Reduce space complexity of 0-1 Knapsack problem

### ISSUE THREAD

**Issue by Manan-09** [TheAlgorithms/C-Plus-Plus#2604]
### Detailed description

We can implement 0-1 knapsack problem in O(C) space complexity  , where C is weight capacity of items we are allowed to take.

As in DP table we are only interacting with above row , we just have to store one row of information , so we can reduce space complexity here.

Here is reference in which I optimised [Java implementation](https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/dynamicprogramming/Knapsack.java) for this problem 

### Context

Current implementation takes O(N * C) space complexity, which is not the optimal, we can gain same result with same Time complexity and reduced space compexity.

**Comment by AniketShirou** [comment]
Please Assign This Issue To Me

**Comment by Manan-09** [comment]
@AniketShirou , actully I cannot assign this to you but you work on it, No problem.

**Comment by harjasae2001** [comment]
I have done this problem and variations of this problem too and I am quite familiar with the concept of using two separate vectors and updating them one by one. Kindly please assign this issue to me.
