### ISSUE TITLE
MorrisPreOrder Traversal

### ISSUE THREAD

**Issue by mkhuzaima** [TheAlgorithms/C-Plus-Plus#2621]
### Detailed description

Morris Traversal is an algorithm for Binary tree traversal in `O(1)` space. 

https://en.wikipedia.org/wiki/Tree_traversal

### Context

It can help users to understand how morris traversal works, and how it can be used for preorder traversal.Morris

### Possible implementation

It is implemented with threaded traversal. i.e., changing tree internally during traversal and restoring it to original state.

**Comment by NSK07** [comment]
Hi Muhammad, I can implement the algorithm in C++. If this is the requirement can you please assign the issue to me?

Regards,
Sharan
