### ISSUE TITLE
Implementing Priority Queue

### ISSUE THREAD

**Issue by AbhirajBose** [TheAlgorithms/C-Plus-Plus#2629]
### Detailed description

In this issue,I will be adding the code of how a priority queue can be implemented.
A priority queue is a type of queue which arranges elements based on their priority values.Elements with higher priority values are typically retrieved before elements with lower priority values.
So,here we will learn the implementation of Priority Queue using Linked List.
Linked List is a type of data structure which consists of a node which has two parts,data and next.The data part of the Linked List stores the value that the users asks to store and the next part stores the priority in which it is stored.

### Context

The change is important for me because it will help me to contribute to open source programs and enhance my skills in Data Structures and Algorithms.Thus,it will help me in logic building and thus clear my concepts regarding Priority Queue while implementing Linked List.

**Comment by spyv22072000** [comment]
@AbhirajBose  please can you assign me this issue ?

**Comment by Rohxn16** [comment]
i wanna work on this issue.
