### ISSUE TITLE
Wanted to add a separate section for trees question

### ISSUE THREAD

**Issue by YashKesh** [TheAlgorithms/C-Plus-Plus#2652]
### Detailed description

There are several question of trees in c++ that should be added and wanted to create a section for adding the questions

### Context

Leetcode problems and other competitive problems would help in understanding the concepts of trees

### Additional information

Assign the issue to me as i want to work on this

**Comment by NandRabadiya** [comment]
Hey 
I can contribute in this project. I have enough knowledge on algorithms and find myself fit for this. Can you please assign it to me ??
