### ISSUE TITLE
feat: Wanted to add an algorithm for bfs(queue) traversal for a binary tree.

### ISSUE THREAD

**Issue by DevBhatia22** [TheAlgorithms/C-Plus-Plus#2675]
### Detailed description

I couldn't find the bfs traversal and i would be glad to add it my self.

### Context

Because it's an important algo.

**Comment by DevBhatia22** [comment]
@vil02 check please.

**Comment by vil02** [comment]
It seems to be [implemented](https://github.com/TheAlgorithms/C-Plus-Plus/blob/08900b8c983b861ddd9c2e1efe7bf0bdd53beb4a/data_structures/binary_search_tree.cpp#L92).

However, the mentioned file would need a big cleanup (e.g. adding real tests and removing memory leaks).
