### ISSUE TITLE
[FEATURE] Upgrade to C++ 23 Standard

### ISSUE THREAD

**Issue by aminegh20** [TheAlgorithms/C-Plus-Plus#2768]
### Detailed description

I propose upgrading our project's C++ version from C++11 to C++23. 

### Context

- Improved Language Features: C++23 includes modern features like improved constexpr, modules, and enhanced ranges, which can simplify code. 
- Better Performance: Features like coroutines and more efficient constexpr usage can lead to faster and more readable code.
- Future Proofing: Aligning with the latest standard ensures compatibility with modern libraries and keeps the project maintainable.

**Comment by realstealthninja** [comment]
https://github.com/TheAlgorithms/C-Plus-Plus/pull/2746
You can see my proposal for 17 here.
if we update to 23 right now, we will lose [arm compatibility](https://developer.arm.com/documentation/101458/2404/Standards-support/Supported-C-C---standards-in-Arm-C-C---Compiler)
esp has no such [issues](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/cplusplus.html#c-language-standard) though

**Comment by realstealthninja** [comment]
closing since no comment from author.
