### ISSUE TITLE
[FEATURE] Creating a Tic-Tac-Toe game in CPP

### ISSUE THREAD

**Issue by rogerdemello** [TheAlgorithms/C-Plus-Plus#2770]
### Detailed description

This is a Tic-Tac-Toe game in C++.

### Context

This is for the coders/programmers who want to implement Tic-Tac-Toe in C++.

**Comment by AK261102** [comment]
can u assign me this issue

**Comment by Satyam-nitp** [comment]
can you assign this to me.

**Here’s a simplified  description for implementing Tic-Tac-Toe in C++:**

Create a 3x3 board using a 2D array to represent the game grid.
Display the board after each move so players can see the current game state.
Take input from the players (Player 1 = 'X', Player 2 = 'O') for selecting a position on the grid.
Check for a win after each move by verifying if three symbols are aligned in a row, column, or diagonally.
Check for a draw if all positions are filled and no one has won.
Alternate turns between Player 1 and Player 2 until there is a winner or a draw.
Display the result and offer the option to restart the game or exit.

**Comment by AK261102** [comment]
i have updated it

**Comment by ManyaDhingra** [comment]
Hi @rogerdemello !! Can you assign me this issue?

**Comment by NikhilG-14** [comment]
@AK261102 i want to work on this can you assign me  this

**Comment by AK261102** [comment]
tag him bro  @rogerdemello

**Comment by sandeepM-codes** [comment]
can u assign me this issue

**Comment by AnkitGSingh** [comment]
I have already solved it, can you please assign me this  issue

**Comment by Falakejaz786** [comment]
hey @rogerdemello can you assign me this
