### ISSUE TITLE
[FEATURE] Unbounded Knapsack in Dynamic Programming Section

### ISSUE THREAD

**Issue by yeolesanskruti** [TheAlgorithms/C-Plus-Plus#2782]
### Detailed description

I want to add the algorithm of "Unbounded Knapsack" in dp section.

### Context

This covers the infinite supply of objects which is important and different from Knapsack problem.

### Additional information

I am Contributor of Hactoberfest 2024.
Please assign me.

**Comment by realstealthninja** [comment]
just create a pr and link it to this pull request
