### ISSUE TITLE
 Feature Request: Implement Graph Colouring Algorithm

### ISSUE THREAD

**Issue by THIRU-1074** [TheAlgorithms/C-Plus-Plus#2792]
### Detailed description

 I would like to request the implementation of a Graph Colouring Algorithm as a feature in this repository. Graph colouring is a way of assigning labels (often referred to as "colours") to the vertices of a graph such that no two adjacent vertices share the same label. 

### Context

This algorithm has multiple applications, including:

- Scheduling Problems: Assigning timeslots to tasks without conflicts.
- Map Coloring: Ensuring that no two adjacent regions share the same color.
- Register Allocation in Compilers: Minimizing the use of registers in code generation.

### Possible implementation

Implementation of a Greedy Graph colouring Algorithm as a baseline. This algorithm assigns the smallest possible colour to each vertex while ensuring that no two adjacent vertices share the same colour.
Additionally, an implementation of Backtracking can be provided to find more optimal solutions for graphs that require a minimal number of colours.

### Additional information

(https://en.wikipedia.org/wiki/Graph_coloring)

**Comment by ritk20** [comment]
Implementation of graph colouring using backtracking exists [here](https://github.com/TheAlgorithms/C-Plus-Plus/blob/512efd18610531000e28600e03e6ddc42c56cfe0/backtracking/graph_coloring.cpp). I guess other colouring algorithms can be added.

**Comment by THIRU-1074** [comment]
Yes , DSatur is good to be implemented, this algorithm has better performance compared to existing one in repo.
