### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Aliqyan-21** [TheAlgorithms/C-Plus-Plus#2806]
### What is the Karatsuba Algorithm?
The Karatsuba algorithm is a fast multiplication algorithm that was discovered by Anatolii Alexeevitch Karatsuba in 1960. It is a divide-and-conquer algorithm that reduces the multiplication of two n-digit numbers to three multiplications of n/2-digit numbers, along with some additions and shifts.

### Context

Karatsuba's Fast Multiplication is a **Mathematics Algorithm** which will fit in the math section of the repository.

### Algorithm Details
The algorithm works as follows:

If either of the input numbers is less than 10, it performs a simple multiplication.

Otherwise, it splits the input numbers into two halves and recursively applies the algorithm.

It calculates the product of the two numbers using the formula:
x _ y = (a _ c) _ 10^n + ((a + b) _ (c + d) - a _ c - b _ d) _ 10^(n/2) + b _ d

**where:**

a, b, c, d are the respective halves of the input numbers.
n is the number of digits in the input numbers.

## Additional Information:

This will be my implementation of the Karatsuba multiplication algorithm in C++. This implementation is my interpretation of the algorithm, according to me this is the easiest implementation out there, easier then what was on [gfg](https://www.geeksforgeeks.org/karatsuba-algorithm-for-fast-multiplication-using-divide-and-conquer-algorithm/) atleast.

Please assign me this issue with the label **`Hacktoberfest`**.

**Comment by ritk20** [comment]
It is already [present](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/divide_and_conquer/karatsuba_algorithm_for_fast_multiplication.cpp) 

However if you feel that your implementation is better, I think you can make a pr suggesting modification or maybe even a new implementation according to CONTRIBUTING.md. Better consult a maintainer.

**Comment by Aliqyan-21** [comment]
Ohh ok @ritk20 I am sorry for not checking it before.

**Comment by Aliqyan-21** [comment]
I'll close the issue.
