### ISSUE TITLE
adding interview quetions. 

### ISSUE THREAD

**Issue by Abhirajtiwari1** [TheAlgorithms/C-Plus-Plus#2828]
### Detailed description

though the repo consist of all the possible alogorithms existing today but their demonstration in solving the problems asked in big tech companies will be much better. 

### Context

This change should considered as important because if a person accessing the repo will get access to the interview quetions than they will implement the algorithms in those quetions at the same time helping them in buiding confidence when it comes to competitive programming. 

### Possible implementation

accept the pull requests on the repo which are proposing an interview quetions.

**Comment by realstealthninja** [comment]
unfortunately we'll have to push this to a later date #2450 already exists
