### ISSUE TITLE
Add algorithm to find lcm (least common multiple).

### ISSUE THREAD

**Issue by msk4862** [TheAlgorithms/C-Plus-Plus#283]
Algorithm for finding lcm(least common multiple) is not added.

**Comment by shubhamkakkar** [comment]
I am taking this issue

**Comment by anshal570** [comment]
I want to work on this issue.

**Comment by Kunal614** [comment]
I want to work on this issue.

**Comment by Kunal614** [comment]
> I want to work on this issue.

 i have done a pull request  for this
 https://github.com/TheAlgorithms/C-Plus-Plus/pull/526

**Comment by karpit14** [comment]
I want to pull request this as i am interested to work on this.

**Comment by fhlasek** [comment]
Resolved by now
https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/least_common_multiple.cpp
