### ISSUE TITLE
This is not have any Binary Tree folder

### ISSUE THREAD

**Issue by keshavagr025** [TheAlgorithms/C-Plus-Plus#2838]
### Detailed description

Sir, i need to to work on that folder of Binary tree i have a knowledge about the Trees and BST please asgin to me.

### Context

I give Proper Folder of Binary Trees and gives important question on that

### Possible implementation

I have lots of logic to BT to Apply in CP.

### Additional information

Give Maximun codes of BT

**Comment by realstealthninja** [comment]
we dont need a folder for binary tree. If you want to operations on a binary tree use the
operation on data structures folder.
