### ISSUE TITLE
Added 4Sum.cpp

### ISSUE THREAD

**Issue by shubhamjain1402** [TheAlgorithms/C-Plus-Plus#2865]
### What would you like to share?

Added the solution to the leetcode 4Sum problem to the others section.

### Additional information

PR[#2864]

**Comment by ayeshamansoor18** [comment]
I'm here to solve this query

**Comment by shubhamjain1402** [comment]
Hi @ayeshamansoor18,

I have added the solution to the 4 Sum problem on LeetCode to the “Others” section of the repository and created PR [#2864] as part of Hacktoberfest. I would be grateful if you could take a moment to review it.
