### ISSUE TITLE
Add Job Sequencing Algorithm in c++

### ISSUE THREAD

**Issue by sneha0099** [TheAlgorithms/C-Plus-Plus#2881]
### Detailed description

I would like to implement the Job Sequencing Algorithm in C++ as part of the repository's collection of algorithms. This algorithm is used to maximize profit by scheduling jobs within their respective deadlines.

### Context

The Job Sequencing Algorithm is a popular greedy algorithm often applied in scheduling and resource allocation problems. It is especially useful when each job has an associated deadline and profit, with the aim to sequence jobs to maximize profit. This algorithm could be a valuable addition for learners and developers, providing an efficient approach to similar scheduling problems.

**Comment by sneha0099** [comment]
/ assign

**Comment by Serioton-codes** [comment]
Do you want the algorithms to also report the order of the jobs or just the maximum profit we can make ?
