### ISSUE TITLE
Add Combinatorics folder and algorithms

### ISSUE THREAD

**Issue by Kushagra-0801** [TheAlgorithms/C-Plus-Plus#306]
Add a Combinatorics category and algorithms like permutations, combinations, powerset etc

**Comment by Kushagra-0801** [comment]
I would like to implement the combinations algorithm

**Comment by fhlasek** [comment]
@Kushagra-0801 I believe such an algorithm would fit nicely in `math` folder. If you find a missing algorithm that you'd like to add, please follow the [CONTRIBUTING](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md) guidelines to add it.
