### ISSUE TITLE
Added Linked_List_Insertion_sort.cpp

### ISSUE THREAD

**Issue by Anshuvats** [TheAlgorithms/C-Plus-Plus#361]
Sorting a Linked List using Insertion Sort in C++.

**Comment by sagnik-chatterjee** [comment]
taking up this issue ...

**Comment by sagnik-chatterjee** [comment]
Is the linked list only single linked list ?

**Comment by PbChauhan** [comment]
@Anshuvats I want to take this issue and will upload PR sortly.

**Comment by Anshuvats** [comment]
@PbChauhan Yeah, Go ahead.

**Comment by vj-codes** [comment]
@Panquesito7 hey I would like to work on this!

**Comment by deepanshumidha5140** [comment]
@Panquesito7 hey I would like to work on this!

**Comment by gaurav-iitb** [comment]
I Would also like to work on this

**Comment by mishraabhinn** [comment]
> @Panquesito7 hey I would like to work on this!

@vj-codes  assigned

**Comment by hd2342-dubey** [comment]
Hello, I want to work over this, please assign it to me.

**Comment by mishraabhinn** [comment]
> Hello, I want to work over this, please assign it to me.

I guess someone is already working on this. Thanks

**Comment by PrakarshSingh5** [comment]
hi can you assign this to me

**Comment by BugsBunny-PG** [comment]
Hello Maintainer,
I want to solve this problem ,please assign this issue to me.

**Comment by SourishJoshi8** [comment]
Hello,
Can u plz assign this issue to me?
