### ISSUE TITLE
Added Euler Totient function in cpp

### ISSUE THREAD

**Issue by Jawed-byte** [TheAlgorithms/C-Plus-Plus#367]

**Comment by namannimmo10** [comment]
@Jawed-byte I wanna work on this! Please assign the issue to me.

**Comment by Aakash1822** [comment]
@namannimmo10 Nothing is described by him. I implemented this code. Go to repository and check it out.

**Comment by PradyumnG** [comment]
@fhlasek Can you assign this to me so that I can work on it?

**Comment by Panquesito7** [comment]
Please **don't ask** to be assigned. See the [contributing guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#contributor).
If you want to help with this, submit a PR or contact the admins to work on it.

Thank you. 🙂

**Comment by kgpjay** [comment]
would love to take a stab at this :)

**Comment by mishraabhinn** [comment]
> Please **don't ask** to be assigned. See the [contributing guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#contributor). If you want to help with this, submit a PR or contact the admins to work on it.
> 
> Thank you. 🙂



> would love to take a stab at this :)

Please don't ask to be assigned. See the [contributing guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#contributor).
If you want to help with this, submit a PR or contact the admins to work on it.

Thank you. 🙂

**Comment by Sounakray2003** [comment]
I would like to contribute

**Comment by realstealthninja** [comment]
This was already implemented by #714
and should probably be closed.
