### ISSUE TITLE
Added Fermat_Little_Theorem in cpp

### ISSUE THREAD

**Issue by Jawed-byte** [TheAlgorithms/C-Plus-Plus#369]

**Comment by namannimmo10** [comment]
@Jawed-byte  Hey, I can implement this. :)

**Comment by tjgurwara99** [comment]
I did this a few years ago, might be worth checking that out from [this link](https://github.com/tjgurwara99/PrimeNumberLibrary/blob/master/libs/prime/prime.cpp)
