### ISSUE TITLE
Added Prims algorithm in cpp

### ISSUE THREAD

**Issue by Jawed-byte** [TheAlgorithms/C-Plus-Plus#371]

**Comment by UltraWelfare** [comment]
I see that this is still not done, so I'll try to do it.

**Comment by EkanshMangal** [comment]
Can anyone tell me in which folder we have to add this algorithm if issue is still open?

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/graph/prim.cpp
