### ISSUE TITLE
Error in Circular queue operations

### ISSUE THREAD

**Issue by Tawishi** [TheAlgorithms/C-Plus-Plus#468]
This is regarding an error in the file having path   Operations on Datastructures/Circular Linked List.cpp  
The Print option in the menu shows the last element entered as Not Found.
![result](https://user-images.githubusercontent.com/55306738/66430324-747d9980-ea37-11e9-8a43-5bdf396cd3ef.jpg)
I would like to resolve this issue.

**Comment by Baranixowy** [comment]
I think that I fixed this.

**Comment by Tawishi** [comment]
The error was there as is seen in the image.

**Comment by Baranixowy** [comment]
Now it should working.
