### ISSUE TITLE
 Added algorithm to find lcm (least common multiple).

### ISSUE THREAD

**Issue by Kunal614** [TheAlgorithms/C-Plus-Plus#548]

**Comment by tjgurwara99** [comment]
Since the GCD algorithm for integers is already there, is there really a need for LCM?
For example:
For any a,b integers, let g = gcd(a,b) and l = lcm(a,b) then it is easy to prove that g x l = a x b

**Comment by abhaysachan619** [comment]
a*b=LCM(a,b)*GCD(a,b)
Then LCM(a,b)=(a*b)/GCD(a,b)

**Comment by abhaysachan619** [comment]
a*b=LCM(a,b)*GCD(a,b)
LCM(a,b)=(a*b)/GCD(a,b)

**Comment by cclauss** [comment]
Lots of talk but no pull requests:
https://github.com/TheAlgorithms/C-Plus-Plus/search?q=lcm&type=Issues

**Comment by tjgurwara99** [comment]
@cclauss I created one, couldn't pass the automated lint test that each pull request goes through so I deleted pull request even though I passed the exact same test on my machine. Any suggestions what I may have been missing?

**Comment by cclauss** [comment]
Yes.  My suggestion is to not give up so easily.  Leave PRs open and ask for help in understanding why the are failing and how to fix the failing code.  Closing the pull request gets you no closed to landing your algorithm.

**Comment by tjgurwara99** [comment]
This is solved in #840
