### ISSUE TITLE
Added find factors of any number in Osqrt(n) time

### ISSUE THREAD

**Issue by Kunal614** [TheAlgorithms/C-Plus-Plus#570]
https://github.com/Kunal614/C-Plus-Plus/commit/05d8f9e29219aa0836cdff455d3926403828f7ac

**Comment by Baranixowy** [comment]
Check my update.

**Comment by Kunal614** [comment]
What you updated?

**Comment by Baranixowy** [comment]
change prime factor finder and add all divider function

**Comment by Kunal614** [comment]
Ok that's good.
If you have different algorithm then add it.

**Comment by gaushikmr** [comment]
@Kunal614 Can u assign me

**Comment by gaushikmr** [comment]
@Kunal614 Can I work with this issue

**Comment by Kunal614** [comment]
@gaushikmr Yes
