### ISSUE TITLE
Add format for PR and contribution guide?

### ISSUE THREAD

**Issue by bhaumikmistry** [TheAlgorithms/C-Plus-Plus#572]
We should add a format for PR description to keep the PR in same format easy to read, and some more detailed contribution guide and Welcome bot for betterment and encouragement?

Please advice. @AnupKumarPanwar 

Once you advice please assign it back to me.

-Thanks.

**Comment by mitsuan** [comment]
Can I contribute to this project?

**Comment by Kunal614** [comment]
can i contribute?

**Comment by Kunal614** [comment]
> can i contribute?
Updated at readme https://github.com/Kunal614/C-Plus-Plus/commit/1dce03efd9fdd8f925ab77ad8f5a55cc518c390a

**Comment by bhaumikmistry** [comment]
Please take a look at the README of [python](https://github.com/TheAlgorithms/Python) for better understanding of what we want.

**Comment by AnupKumarPanwar** [comment]
We can create an issue template and PR template rather than adding the complete format in contribution guidelines.
