### ISSUE TITLE
Can you do Korean annotation?

### ISSUE THREAD

**Issue by swkikb** [TheAlgorithms/C-Plus-Plus#624]
Thank you for revealing software that is generally neat and has many features.
However, this data is not easily accessible to Korean users, so is it OK to add Korean annotations?

**Comment by Arctic2333** [comment]
저는 프로그래머로서 영어를 잘 배워야 할 것 같아요.

**Comment by flying-kiter** [comment]
If you really wanna learn programming well, I suggest you improve English skill for further development.

**Comment by cclauss** [comment]
@swkikb You could ___fork___ this repo to create a separate copy that has Korean annotations.
