### ISSUE TITLE
ADD sort(arr,arr+n,comaprator) inbuilt c++ function

### ISSUE THREAD

**Issue by sarimurrab** [TheAlgorithms/C-Plus-Plus#717]
## Detailed Description
Add a program of sorting using inbuilt c++ sort function

## Context

1. More will get to know about the comparator function. 
2. How comparator function sort in lexical order and how to improve it.

## Possible Implementation
```
bool compare(string a, string b)
{
    cout << "Comparing " << a << " and " << b << endl;
    if (a.length() == b.length())
        return a < b;
    return a.length() < b.length();
}
```
`    sort(arr, arr + n, compare);`

**Comment by sarimurrab** [comment]
How can I become a member of this organization.?

**Comment by cclauss** [comment]
Ask on https://gitter.im/TheAlgorithms

**Comment by muhammad8584** [comment]
Incredible

**Comment by Gopal-Dahale** [comment]
Can I work on this if it is open?

**Comment by cclauss** [comment]
Anyone can work on it.  Everything is open...  this is open source.  Submit a pull request and it will be reviewed.

**Comment by kvedala** [comment]
Wouldn't this be an *example of how to use `std::sort`* and not an algorithm?
There are examples on almost every STL library website.
[see example](https://lmgtfy.com/?q=std%3A%3Asort&s=d&iie=1)

**Comment by fhlasek** [comment]
Agree with @kvedala, I don't see a clear added value of the proposed program.
