### ISSUE TITLE
Add bottom-up non-recursive merge sort

### ISSUE THREAD

**Issue by Albirair** [TheAlgorithms/C-Plus-Plus#728]
I have an implementation of bottom-up merge sort that I'd like to share with you. It has exactly the same space and time complexity of the regular algorithm, except it doesn't overwhelm the stack with recursion.
Furthermore, my code uses templates for generic sorting of any data structure and, it is well-documented and uses Doxygen in case a person would like to auto-generate documentation.

**Comment by cclauss** [comment]
Sounds awesome!  No need to open an issue...  You can just directly create a pull request.

Should we use Doxygen more broadly across the repo?  Maybe make a [GitHub Action](../master/blob/.github/workflows) that autogenerates docs on pull requests?

**Comment by Albirair** [comment]
That's great, I will a pull request.
Regarding Doxygen, it would be amazing to use it across the repo either for generation of documentation or facilitating programming since IDE can recognize it and display its information as needed. Although, I don't feel excited about making such documentation be generated on GitHub, due to increasing repo size and the fact it can be generated locally.

**Comment by cclauss** [comment]
Let's try to automate Doxygen for just one algorithm to see how it works and determine its efficacy.
