### ISSUE TITLE
[FEATURE] Addition of statistical and probability distribution functions

### ISSUE THREAD

**Issue by deadshotsb** [TheAlgorithms/C-Plus-Plus#751]
Addition of statistical and probability distribution functions

## Detailed Description

I saw the Probability file in the repository and only basic operations (addition rule) to calculate probability was given. Addition to this function, we can add statistical distribution functions like Gaussian Normalization, Binomial Distribution, etc classes and provide some addition functions to incorporate  the changes in basic statistical features (mean , variance, standard deviation) for each distribution.

## Context

The observation of distribution functions are very much helpful in case of statistical calculations which is more advanced in case of Python but is lagging in C++. 

## Possible Implementation

Using basic class concept with inheritance we can easily add different distribution features and effectively calculate the statistical features using them.

**Comment by sagnik-chatterjee** [comment]
Although the normal distribution is present under random library as std::normal_distribution , should i just add an implementation from the ground up or implement that directly?

**Comment by deadshotsb** [comment]
In case of std::normal_distribution, it is effective in calculating the standard deviation and mean of the distribution. But if we can extend the present scenario to calculate the std deviation and mean of not one but N of those distributions in an optimised way. I checked in the probability file of this repository but there is no reference of distribution functions, so this has to be done from ground up I suppose. This can be a great addition while working with some large files (with rapid additions) without starting from beginning.

**Comment by cclauss** [comment]
Also feel free to create new versions of functions that are already in the standard library if you thing your reimplementation can educate others.
