### ISSUE TITLE
Suggestion -  use modern c++

### ISSUE THREAD

**Issue by htr751** [TheAlgorithms/C-Plus-Plus#753]
Maybe try rewrite the code in more modern c++ (or make another repository for this).
I didn't look through all the files but it seems that you are using c++98 and its very old c++ standart (try using at least c++11)

**Comment by cclauss** [comment]
Would these changes make the code run faster or reduce the size of the executables?

**Comment by htr751** [comment]
Some of them actually will make it faster. For example, if you made linked list as a class (and not as global methods) than as part of adding constructors you could add move consturctor which in case you want to transfer ownership of the list to some other list is much faster than copying it. I know its not part of the data stracture implementation but the all point in making it in multiple languages is to show how to implement such things in different languages isn't it (and in such case I think it's important to use best practices when implementing it)?

Another example is using smart pointers like unique_ptr to handle ownership of memory in your code. While this won't make it faster (nor will make it slower) it will save you the need to delete all the allocated on the heap pointers and it will make the code more beautifull.

**Comment by cclauss** [comment]
My recommendation is that we take an algorithm-by-algorithm approach to such a conversion where each pull request modifies only one algorithm and demonstrates that the algorithm is faster, easier to understand, or generates less code than the current version.  Side-by-side benchmarks are much appreciated to demonstrate the efficacy of the new approach.

**Comment by ayaankhan98** [comment]
with the new versions of C++ i observed one thing, earlier i was using C++14 to write codes for codeforces and Codechef problems and on submissions those codes are takiing memory of about 15M but when i compiled those same codes using -std=c++17 flag the memory consumed is decreased to 5M,
i think it will be a good idea to use the C++17 standard

**Comment by offamitkumar** [comment]
I would like to work on it. Please assign this to me.

**Comment by cclauss** [comment]
Please read CONTRIBUTION.md.  This repo does not assign tasks to people.  Instead it accepts pull requests.

**Comment by offamitkumar** [comment]
still my pull request for #789  is not accepted. How I'm Supposed to contribute further, As per rule one cpp change per commit.

**Comment by kvedala** [comment]
I think this can be closed now. The C++ standard for compilation, etc have been standardized for each and every file and tested on three platforms. 

C++11, though old, allows to implement the algorithms from the repo directly on small microcontrollers running on RTOS and not relying on linux or other larger OS kernels.
