### ISSUE TITLE
Algorithm for finding Connected Components in graph is not present

### ISSUE THREAD

**Issue by ayaankhan98** [TheAlgorithms/C-Plus-Plus#755]
i would like to work on this.

**Comment by cclauss** [comment]
Please do not wait for permission. Just go ahead and submit pull requests for review.

**Comment by ayaankhan98** [comment]
okay sure

**Comment by deadshotsb** [comment]
good work @ayaankhan98

**Comment by cclauss** [comment]
Which pull request closed this issue?

**Comment by deadshotsb** [comment]
@cclauss pull request #761 is used to resolve this issue
