### ISSUE TITLE
Algorithm for finding strongly connected components is not present

### ISSUE THREAD

**Issue by ayaankhan98** [TheAlgorithms/C-Plus-Plus#756]
i would like to work on this.

**Comment by cclauss** [comment]
Please do not wait for permission. Just go ahead and submit pull requests for review.

**Comment by ayaankhan98** [comment]
okay sure

**Comment by ayaankhan98** [comment]
it seems that we already have kosaraju implementation for the same problem

https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/graph/kosaraju.cpp

therefore closing this issue
