### ISSUE TITLE
[FEATURE] Bellaman-Ford Algorithm not present

### ISSUE THREAD

**Issue by ayaankhan98** [TheAlgorithms/C-Plus-Plus#757]
## Detailed Description
Bellaman Ford algorithm for finding shortest path in graphs contaning negative weight edges is not present.

i wish to work on this

**Comment by cclauss** [comment]
Please do not wait for permission. Just submit pull requests for review. Thanks.

**Comment by ayaankhan98** [comment]
okay sure

**Comment by cclauss** [comment]
Actually... https://github.com/TheAlgorithms/C-Plus-Plus/search?q=ford

**Comment by ayaankhan98** [comment]
oh okay it's there in Dynamic programming directory
