### ISSUE TITLE
Postfix and prefix calculators are not present

### ISSUE THREAD

**Issue by shashank-vats** [TheAlgorithms/C-Plus-Plus#758]
Algorithms to calculate postfix and prefix expression are not present. I wish to work on this.

**Comment by cclauss** [comment]
Please do not wait form permission.  Just go ahead and submit pull requests for review.

**Comment by coderanant** [comment]
@cclauss  It would be really good if issues can instead be assigned.
It's difficult to know if somebody is working on an issue this way.

**Comment by mursalfk** [comment]
Okay... thanks @cclauss

**Comment by Rameshwar3297** [comment]
I want to work on this algorithms. I can add algorithms to calculate postfix and prefix expression. Can i do ?? @
