### ISSUE TITLE
sqrt has problem with number lower than 1

### ISSUE THREAD

**Issue by zivzhen** [TheAlgorithms/C-Plus-Plus#760]
sqrt has problem with number lower than 1

**Comment by cclauss** [comment]
Which one?  https://github.com/TheAlgorithms/C-Plus-Plus/search?q=sqrt. Please provide some test cases than fail.

**Comment by ayaankhan98** [comment]
i think he is talking about `math/sqrt_double.cpp`
i tested this for input of `0.2` and `0.5`, it seems that the program goes into infinite loop

**Comment by cclauss** [comment]
@DarkWarrior703 Your feedback on this please?

**Comment by EkanshBhatnagar** [comment]
How can I fix this issue? I want to be a contriubutor.

**Comment by cclauss** [comment]
Closed in #768
