### ISSUE TITLE
Union-Find algorithm for finding components of a Graph

### ISSUE THREAD

**Issue by deadshotsb** [TheAlgorithms/C-Plus-Plus#764]
A DFS approach has been added for finding the number of components of a graph, but an approach using Union-Find algorithm is more than welcomed. 

An Union-Find Approach using rank or path-compression can be a better solution

**Comment by cclauss** [comment]
We want a benchmark that ___proves___ that it is a better solution.

**Comment by ayaankhan98** [comment]
i want to work on this.

**Comment by coderanant** [comment]
I was just wondering how "Union-Find Approach using rank or path-compression" could be a better approach in finding the number of connected components. It'll take O(n log n) while the dfs approach works in O(n).
Union-Find Structure (DSU) is rather generally used for the case where we are given several elements, each of which is a separate set. A DSU will have an operation to combine any two sets, and it will be able to tell in which set a specific element is and can create a set from a new element.
An implementation describing this use of DSU would be more helpful.

**Comment by cclauss** [comment]
Why write all this ___theoretical___ text??  Write up both algorithms and a benchmark instead.

**Comment by coderanant** [comment]
I have added Pull Request #773 regarding this issue.

**Comment by deadshotsb** [comment]
@coderanant  DFS will take O(E) and O(E) = [O(V), O(V2)].

**Comment by coderanant** [comment]
@deadshotsb Sorry for not making it clear.
DFS will take O(E) = [O(V), O(V<sup>2</sup>)]
DSU will take O(E) = [O(V log(V)), O(V<sup>2</sup> log(V))]
I have however added approach with both Union by size of tree and Path Compression which might work very closer to DFS approach in most cases.

**Comment by cclauss** [comment]
Where is the benchmark?

**Comment by coderanant** [comment]
How am I supposed to write a benchmark?
Please pardon if this is very intuitive as I am kinda new to Open Source.

**Comment by deadshotsb** [comment]
@coderanant The best method to write a benchmark according to test the algorithms based on some randomly generated Graphs and showing  a relation between time and the size of graph for the algorithms under consideration.

**Comment by ayaankhan98** [comment]
what is the current status of this issue, as far as i know i had merged the PR related to this issue, what the status of benchmark @coderanant ?

**Comment by testitem** [comment]
> I was just wondering how "Union-Find Approach using rank or path-compression" could be a better approach in finding the number of connected components. It'll take O(n log n) while the dfs approach works in O(n).
> Union-Find Structure (DSU) is rather generally used for the case where we are given several elements, each of which is a separate set. A DSU will have an operation to combine any two sets, and it will be able to tell in which set a specific element is and can create a set from a new element.
> An implementation describing this use of DSU would be more helpful.

Let's say you are given Q queries. Each query is to add an edge into a graph. After each query you are to return the amount of connected components in this graph.

DFS is O(NQ), while DSU is (Q a(N)).

**Comment by kvedala** [comment]
> > I was just wondering how "Union-Find Approach using rank or path-compression" could be a better approach in finding the number of connected components. It'll take O(n log n) while the dfs approach works in O(n).
> > Union-Find Structure (DSU) is rather generally used for the case where we are given several elements, each of which is a separate set. A DSU will have an operation to combine any two sets, and it will be able to tell in which set a specific element is and can create a set from a new element.
> > An implementation describing this use of DSU would be more helpful.
> 
> Let's say you are given Q queries. Each query is to add an edge into a graph. After each query you are to return the amount of connected components in this graph.
> 
> DFS is O(NQ), while DSU is (Q a(N)).

Since this repository is presenting multiple algorithms from an educational perspective, older inefficient algorithm implementations would also be welcome along with faster and more efficient implementations.

**Comment by testitem** [comment]
In that case I am confused as for why cclauss is obsessed with speed benchmarks.

**Comment by cclauss** [comment]
We want to be able to see the ___theoretical___ performance __DFS is O(NQ), while DSU is (Q a(N))__ as well as the ___actual___ performance 32 sec. vs. 97 sec.

**Comment by coderanant** [comment]
> > I was just wondering how "Union-Find Approach using rank or path-compression" could be a better approach in finding the number of connected components. It'll take O(n log n) while the dfs approach works in O(n).
> > Union-Find Structure (DSU) is rather generally used for the case where we are given several elements, each of which is a separate set. A DSU will have an operation to combine any two sets, and it will be able to tell in which set a specific element is and can create a set from a new element.
> > An implementation describing this use of DSU would be more helpful.
> 
> Let's say you are given Q queries. Each query is to add an edge into a graph. After each query you are to return the amount of connected components in this graph.
> 
> DFS is O(NQ), while DSU is (Q a(N)).

Thanks for the clarification.
I didn't consider this use-case.

**Comment by Chillee** [comment]
If the "point" of this repo is to present algorithms from an "educational" perspective, what use are benchmarks?

On a similar note, if the goal is to present algorithms from an "educational" perspective, the repo should do a better job of documenting/explaining each algorithm.

**Comment by kvedala** [comment]
> If the "point" of this repo is to present algorithms from an "educational" perspective, what use are benchmarks?
> 
> On a similar note, if the goal is to present algorithms from an "educational" perspective, the repo should do a better job of documenting/explaining each algorithm.

Documentation is being updated. A major re-work in these regards can be found here https://kvedala.github.io/C-Plus-Plus. However, for this documentation to automatically stay up-to-date with latest commits, the code submitted must be properly structured and documented.

**Comment by kvedala** [comment]
> > If the "point" of this repo is to present algorithms from an "educational" perspective, what use are benchmarks?
> > On a similar note, if the goal is to present algorithms from an "educational" perspective, the repo should do a better job of documenting/explaining each algorithm.
> 
> Documentation is being updated. A major re-work in these regards can be found here https://kvedala.github.io/C-Plus-Plus. However, for this documentation to automatically stay up-to-date with latest commits, the code submitted must be properly structured and documented.

Also, any help towards this herculean effort would be greatly appreciated 😅

**Comment by kvedala** [comment]
> If the "point" of this repo is to present algorithms from an "educational" perspective, what use are benchmarks?
> 
> On a similar note, if the goal is to present algorithms from an "educational" perspective, the repo should do a better job of documenting/explaining each algorithm.

@Chillee 
The benchmarks can be included in the documentation of the code. It is helpful for any reader to understand how one implementation of a solution to a particular problem is better or worse than the other. If the author of the code is able to describe that in detail, excellent. Even without it, the reader can review, compare, test and come to their own conclusions as to which code suits them better and why. Is this is not education? 😄

**Comment by UtkarshBhatthere** [comment]
> If the "point" of this repo is to present algorithms from an "educational" perspective, what use are benchmarks?
> 
> 
> 
> On a similar note, if the goal is to present algorithms from an "educational" perspective, the repo should do a better job of documenting/explaining each algorithm.

Because Benchmarks themselves are a part of the said explanation/ documentation.
