### ISSUE TITLE
[BUG]SegFault in remove(x) DLL

### ISSUE THREAD

**Issue by f0lg0** [TheAlgorithms/C-Plus-Plus#765]
## Description

the remove() function throws a segmentation fault. 

## Expected Behavior

The function should remove the parsed element.

## Actual Behavior

The function fails at "t->prev->next = t->next;" and throws a seg fault

## Possible Fix

Still working on it, just wanted to report it... I don't know C++ well.

## Steps to Reproduce

1. insert some values
2. print if you want
3. delete something

## Context

I was trying to remove a node from the DLL

**Comment by ayaankhan98** [comment]
@f0lg0 could you please provide the file link ?

**Comment by f0lg0** [comment]
@ayaankhan98 
 https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/data_structure/Doubly%20Linked%20List.cpp

**Comment by SamratDe** [comment]
I would like to work on this issue.

**Comment by ayaankhan98** [comment]
@SamratDe go ahead
