### ISSUE TITLE
[FEATURE] Negative weight cycle detection

### ISSUE THREAD

**Issue by ayaankhan98** [TheAlgorithms/C-Plus-Plus#766]
## Detailed Description
it looks like we don't have any algorithm to detect the negative weight cycle in graphs

## Possible Implementation
we can implemnt this using Bellaman-Ford algorithm.
Bellaman-Ford Algorithm gives the shortest path from a given source node to all other nodes in |V|-1 iterations (where V is the number of vertex or nodes in graph), if we perform one more iteration of Bellaman-Ford algorithm that is the V-th iteration and if distance of any node gets improved in this V-th iteration then it seems like we have a negative cycle in the graph

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/dynamic_programming/Bellman-Ford.cpp
