### ISSUE TITLE
Rabin Karp Algorithm for String Matching 

### ISSUE THREAD

**Issue by offamitkumar** [TheAlgorithms/C-Plus-Plus#775]
In the C++ string section, the implementation of Rabin Karp algorithm is missing. 

I would like to work on it.

**Comment by cclauss** [comment]
Please review #279 and let us know if we should merge that.

**Comment by offamitkumar** [comment]
Yes we can, after some modification and cleaning the code a little bit.

**Comment by offamitkumar** [comment]
should I create a pull request then?

**Comment by cclauss** [comment]
Yes please.
