### ISSUE TITLE
[Suggestion] Better Implementation for BST

### ISSUE THREAD

**Issue by offamitkumar** [TheAlgorithms/C-Plus-Plus#777]
There could be a better Implementation for BST, which will give more abstraction. Possible implementation, by using an Object Oriented approach instead of a functional programming approach.

**Comment by cclauss** [comment]
Cool.  Let’s keep both the functional and the oop implementation in the repo.  It would be good to be able to study them side-by-side and run relative performance benchmarks on them.

**Comment by Dharni0607** [comment]
Hi, I would like to implement the OOP approach. Can I proceed?

**Comment by Panquesito7** [comment]
> Can I proceed?

Sure, please create a PR in order to get started.
Thank you for your help.
