### ISSUE TITLE
[Improvement] A better Approach for N-Queen Solution 

### ISSUE THREAD

**Issue by offamitkumar** [TheAlgorithms/C-Plus-Plus#780]
in the Backtracking section, there are two solutions for a well-known problem N-Queen. Commit shows that they are improved, but they can be improved further by std:: bitset.

Idea is to store the occupied grid location (for both diagonal and column) into bitset then instead of iterating both diagonals and columns to check whether any location with the same diagonal or column is occupied in the past ,  we can just look up that information in O(1). 

for N = 14 , nqueen.cpp & nqueen_print_all_solutions.cpp took 43 seconds to print all solution , but mine solution with bitset took only 36 seconds.

There isn't much time difference for N=14, but for a bigger N value this can be worse.

**Comment by deadshotsb** [comment]
@offamitkumar You can go ahead.

**Comment by cclauss** [comment]
Can we keep both versions in this repo so that the two versions can be benchmarked?

**Comment by deadshotsb** [comment]
Yes sure

**Comment by offamitkumar** [comment]
@cclauss  created pull request, but due to previous pull request it's showing some error. Would you please help me.

**Comment by cclauss** [comment]
Is this `bits/stdc++.h` or something different?

**Comment by offamitkumar** [comment]
by using std::bitset , it's different from bits/stdc++.h

**Comment by kvedala** [comment]
@offamitkumar do the linked PRs address your concern? If not, feel free to contribute and create a pull-request 🙂

**Comment by fhlasek** [comment]
seems like this had been merged, closing now
