### ISSUE TITLE
[BUG] MorrisInorder file doesn't pass the cpplint tests

### ISSUE THREAD

**Issue by offamitkumar** [TheAlgorithms/C-Plus-Plus#782]
cpplint check on 'MorrisInorder.cpp' reports 107 errors.

**Comment by cclauss** [comment]
Tons of our files fail `cpplint --recursive .` as can be seen from studying our GitHub Action output.  We force modified files to pass the test but that does not fix files that were already in the repo.

The approach of _gradual compliance_ is often used when adding new tests to an existing codebase and we us it here.  If you study our two cpplint GitHub actions, this will become clear.  If you want to attack noncompliant files with [`clang-format`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTION.md#pull-requests) that would be supercool.

**Comment by cclauss** [comment]
Tons of our files fail `cpplint --recursive .` as can be seen from studying our GitHub Action output.  We force modified files to pass the test but that does not fix files that were already in the repo.

The approach of _gradual compliance_ is often used when adding new tests to an existing codebase and we us it here.  If you study our two cpplint GitHub actions, this will become clear.  If you want to attack noncompliant files with
