### ISSUE TITLE
[FEATURE] bridge finding algorithm with Trajan Algorithm

### ISSUE THREAD

**Issue by offamitkumar** [TheAlgorithms/C-Plus-Plus#783]
In graph section, the bridge finding algorithm with Trajan algorithm is not present. 
I would like to implement it.

**Comment by ayaankhan98** [comment]
go ahead @offamitkumar

**Comment by offamitkumar** [comment]
created pull request

**Comment by cclauss** [comment]
@offamitkumar The correct way to do this is to link the PR to the issue by putting `Fixes #783` into the commit message of the pull request.  That will add cross links in both the issue and the pull request and will cause GitHub autoclose the issue when the pull request is merged.

**Comment by offamitkumar** [comment]
Sorry, I don't have much experience with Github. I will change it.

**Comment by cclauss** [comment]
There are two n_queens at https://github.com/TheAlgorithms/C-Plus-Plus/tree/master/backtracking

**Comment by offamitkumar** [comment]
please review #780
