### ISSUE TITLE
[FEATURE] maximum flow algorithm 

### ISSUE THREAD

**Issue by offamitkumar** [TheAlgorithms/C-Plus-Plus#790]
in the graph section,  maximum flow algorithm implementation with Ford Fulkerson & Edmond Karp method are not present.

**Comment by ayaankhan98** [comment]
go ahead and implement, we will be looking for your PR and don't forget to mention this issue #790 in PR

**Comment by offamitkumar** [comment]
@ayaankhan98 my pull request is still not merged, would you please merge it.
