### ISSUE TITLE
to avoid array overflow, use "size -1"？

### ISSUE THREAD

**Issue by iadacm** [TheAlgorithms/C-Plus-Plus#799]
https://github.com/TheAlgorithms/C-Plus-Plus/blob/30eb4bcc7cea6f91c07d1af863fddb1c1521190b/sorting/Quick%20Sort.cpp#L63

**Comment by ayaankhan98** [comment]
@iadacm thanks for reporting the bug

**Comment by ayaankhan98** [comment]
seems to be resolved now
