### ISSUE TITLE
Should this repo lint C++ code with clang-tidy or cpplint?

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/C-Plus-Plus#808]
https://devblogs.microsoft.com/cppblog/intellisense-code-linter-for-cpp
https://devblogs.microsoft.com/cppblog/code-analysis-with-clang-tidy-in-visual-studio
https://github.com/llvm-mirror/clang-tools-extra/tree/master/clang-tidy

v.s.

https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/.github/workflows/cpplint.yml
https://github.com/cpplint/cpplint

**Comment by kvedala** [comment]
`clang-tidy` would be the ideal way to perform static code analysis for this repo as it can be automated fairly easily. I second that. Regarding its implementation:
* a lot of the existing code already fails to either compile or follow the style protocol
* I suggest this change be made once the current errors in the repo are fixed (#805) which addresses this exact problem
* [`.github/workflows/awesome_forkflow.yml`](https://github.com/kvedala/C-Plus-Plus/.github/workflows/awesome_forkflow.yml) attempts to structure the CI implementation flow checking for both static code analysis followed by compilation on multiple platforms

**Comment by kvedala** [comment]
The checks by `clang-tidy` and `clang-format` though quite extensive and flexible, the existing source code is so badly structured that I has been almost impossible to get the repo working well. I have made a preliminary implementation in a branch in my fork - eb4114e2

It can, again, like the `cpplint` be implemented only on the new pull-requests but this will end up making the already incoherent repository even more chaotic. I suggest that the existing repo and the code therein be first normalized as in #805 thereby ensuring that all code does follow at least one standard. The changes can then be applied much more easily thereafter.
