### ISSUE TITLE
[BUG] Duplicate Algorithms

### ISSUE THREAD

**Issue by arpanmukherjee** [TheAlgorithms/C-Plus-Plus#811]
[Binary Indexed Tree](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/range_queries/bit.cpp) and [Fenwick Tree](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/range_queries/FenwickTree.cpp) is essentially same Data Structure.  Remove any one of them please.

**Comment by mishraabhinn** [comment]
Yes both are same. 
Have a look @cclauss.

**Comment by mursalfk** [comment]
Removing on would be better
