### ISSUE TITLE
Gnome sort

### ISSUE THREAD

**Issue by beqakd** [TheAlgorithms/C-Plus-Plus#827]
## Detailed Description
I can see that you dont have implementation of gnome sort algorithm on c++. So i want to contribute it.
## Context
Its one of used sorting algorithm.

## Possible Implementation

with loop as pure gnome sort implementation works.

**Comment by mishraabhinn** [comment]
Go Ahead. 
Will help if needed.

**Comment by beqakd** [comment]
Check fails from this RP is not from my code. I think this code does not has problem with master.
