### ISSUE TITLE
Pythagoras implementation math class.

### ISSUE THREAD

**Issue by beqakd** [TheAlgorithms/C-Plus-Plus#829]
## Detailed Description
I want to implement some math class function as it was so few in folder. I can start by pythagoras function.

## Context
Its one of the most important feature in math so i think its important.

**Comment by PaulinaQuintero** [comment]
Hello! Can I work on pythagoras function? Or is already taken by someone?

**Comment by beqakd** [comment]
Taken by me. will upload it today.

**Comment by PaulinaQuintero** [comment]
Then I can upload a 3d functionality on pythagoras class

**Comment by PaulinaQuintero** [comment]
I can upload the calculation of the complex's module number to complement that folder

**Comment by PaulinaQuintero** [comment]
I did it
#837 
Could you check it?
