### ISSUE TITLE
Change the contributing guidelines name

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C-Plus-Plus#836]
Currently, the name of the file is `CONTRIBUTION.md`.
GitHub does not detect it as contributing guidelines.

However, if we change the name to `CONTRIBUTING.md`, it will work perfectly.
It also suggests users to read contributing guidelines **before** opening a PR or issue.

**Comment by kvedala** [comment]
Thank you for the suggestion. Will add it to the PR - #805 
The file is linked in many places and will need to be reviewed.

**Comment by kvedala** [comment]
Done

**Comment by ayaankhan98** [comment]
this issue seems to be fixed, i am closing this
