### ISSUE TITLE
Implementing Segment Tree Data Structure

### ISSUE THREAD

**Issue by LashaBuxo** [TheAlgorithms/C-Plus-Plus#847]
I'd like to add a Segment Tree Data structure along with other efficient algorithms. I already implemented it, with an example of usage: 

> To Find maximum number on a given interval in an array problem

Soon, I'll make PR. It's already tested locally, and have been added several tests in the script as well.

**Comment by gaushikmr** [comment]
@LashaBuxo Can u assign me to work on this

**Comment by LashaBuxo** [comment]
@gaushikmr I already implemented this part as mentioned in above comments

**Comment by gaushikmr** [comment]
@LashaBuxo Any other works to be done

**Comment by gaushikmr** [comment]
@LashaBuxo SO that I can help you

**Comment by Panquesito7** [comment]
> assign me

Please don't ask to be assigned.
Read the [contributing guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).

**Comment by gaushikmr** [comment]
@Panquesito7 Is there any issues for me to work.I am familiar with C and Python.

**Comment by Panquesito7** [comment]
You can work on them and create a PR, just don't ask to be assigned.
Before submitting, please check previous suggestions, as yours may be a duplicate.

Thank you.
