### ISSUE TITLE
[FEATURE]Why are ciphers not implemented?

### ISSUE THREAD

**Issue by brayo-pip** [TheAlgorithms/C-Plus-Plus#849]
## Detailed Description

I wanted to improve the RSA cipher here, only find out there's none. Before I fork and create that folder is there any specific reason that ciphers haven't been implemented?

**Comment by kvedala** [comment]
There is no reason not to implement. You are welcome to contribute and make the maiden cipher implementation. 😄

**Comment by kvedala** [comment]
I am working on implementing Hill Cipher. 
Others are welcome to contribute as well. 
Closing the issue

**Comment by Panquesito7** [comment]
> Closing the issue

Why close the issue? It is not solved yet.
Others can easily look at it and can help contributing. 🙂

**Comment by kvedala** [comment]
> > Closing the issue
> 
> Why close the issue? It is not solved yet.
> Others can easily look at it and can help contributing. 🙂

The “why” question is answered. For people to contribute, this doesn’t have to be open. Contribute anytime

**Comment by kvedala** [comment]
Also, look here https://github.com/TheAlgorithms/C-Plus-Plus/projects
