### ISSUE TITLE
Addition in Math folder of topic "Babylonian method for square root"

### ISSUE THREAD

**Issue by Anmolreshi** [TheAlgorithms/C-Plus-Plus#851]
I am having the source code and i think implementing it into this would be of great help to others , let me know if you want this contribution into your source code.

**Comment by mishraabhinn** [comment]
Go Ahead.

**Comment by Anmolreshi** [comment]
#851 Adding it

**Comment by kvedala** [comment]
This was implemented in #852 but was closed by author. hence closing this issue
