### ISSUE TITLE
[BUG] Wrong output given by sorting/heap_sort.cpp

### ISSUE THREAD

**Issue by ayaankhan98** [TheAlgorithms/C-Plus-Plus#867]
Program is giving wrong output
## Description

try the program with input 
```
Enter number of elements of array
10
Enter Element 0
-10
Enter Element 1
78
Enter Element 2
-1
Enter Element 3
-6
Enter Element 4
7
Enter Element 5
4
Enter Element 6
94
Enter Element 7
5
Enter Element 8
99
Enter Element 9
0
```
## Expected Behavior

Expected the correct sorted array

## Actual Behavior

getting this wrongly sorted array output
```
Sorted Output
-10
-6
78
7
4
-1
5
0
94
99
```

**Comment by ayaankhan98** [comment]
linked to #873

**Comment by kvedala** [comment]
> linked to #873

Better do it other way - to reference The issue being solved by a pull request in the pull-request description.

**Comment by ayaankhan98** [comment]
> > linked to #873
> 
> Better do it other way - to reference The issue being solved by a pull request in the pull-request description.

okay i will remember that :)
