### ISSUE TITLE
[BUG] wrong output given by sorting/bead_sort.cpp

### ISSUE THREAD

**Issue by ayaankhan98** [TheAlgorithms/C-Plus-Plus#868]
program `sorting/bead_sort.cpp` is producing wrong output
## Description

change the input array from the `main()` to modify the input
suppose this array
```
int a[] = {-10, 78, -1, -6, 7, 4, 94, 5, 99, 0};
```

after changing this now run the program you will get this output
```
0 0 0 0 4 5 7 78 94 99
```

## Expected Behavior

Expected the correct sorted array

## Actual Behavior

getting the worngly sorted array

**Comment by kvedala** [comment]
Was this fixed?

**Comment by ayaankhan98** [comment]
oh sorry for not mentoning the reason of close this issue. actullay i was going through the bead sort algortihm then i came to know that it's impossible to sort the negative integers using this algorithm because the idea on which this is based is something like abacus where there are some beads in the rods of abacus and those beads fall under the influence of gravity to arrange themselves in sorted order and we cannot represent negative numbers there and the example which i tested on this algorithm earlier considers negative integers.

**Comment by ayaankhan98** [comment]
Adding to this we also cannot sort float numbers using this algorithm
