### ISSUE TITLE
[BUG] wrong output given by sorting/bitonic_sort.cpp

### ISSUE THREAD

**Issue by ayaankhan98** [TheAlgorithms/C-Plus-Plus#870]
program when tested with input array
```
int a[] = {-10, 78, -1, -6, 7, 4, 94, 5, 99, 0};
```
produces a output of
```
Sorted array: 
-10 -6 -1 4 0 5 78 94 99 7 
```
which is wrong

## Expected Behavior

Expected a correct sorted array

## Actual Behavior

Showing wrong output

**Comment by farrukhras** [comment]
@ayaankhan98 Bitonic Sort only works on sequences with a length that is in the order of the power of 2 like 4, 8, 16, 32 etc. From what I see, you have given a sequence with length 10, which does not in the order of power of 2. Try changing your input length to something in order of power of 2. It is also specified in the comments of the sorting/bitonic_sort.cpp.

![image](https://user-images.githubusercontent.com/43905121/85759108-5ae9c280-b72a-11ea-8d00-5a48c6e53cf3.png)
