### ISSUE TITLE
[FEATURE] Update README.md  -> Adds list of algorithms separated by topic and in increasing difficulty

### ISSUE THREAD

**Issue by omonimus1** [TheAlgorithms/C-Plus-Plus#883]
## Detailed Description

It could be useful improve the content of the README.md file adding:
* Logo and a link to the [forum room](https://gitter.im/TheAlgorithms) of the community.
* List of all the algorithms shown in different tables, according to the topic, for example:

|Sorting|
|------:|
|[Algorithm 1](README.md)|
|[Algorithm 2](README.md)|

|Searching |
|------:|
|[Algorithm 1](README.md)|
|[Algorithm 2](README.md)|

## Context
*  Listing all the algorithms in increasing difficulty order will be helpful for students and beginners

**Comment by kvedala** [comment]
Great point. Please check the new documentation website:
https://thealgorithms.github.io/C-Plus-Plus 
and its "Files" tab.
Would that address the above concerns?

**Comment by kvedala** [comment]
Feel free to reopen the issue if you think this is not addressed and any suggestions as to why you think it is not fixed would be helpful.
