### ISSUE TITLE
Add branch protection rules

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C-Plus-Plus#887]
It would be nice if this repository could have branch [protection rules](https://help.github.com/en/github/administering-a-repository/configuring-protected-branches) such as required [commit signing](https://help.github.com/en/github/administering-a-repository/about-required-commit-signing), required [status checks](https://help.github.com/en/github/administering-a-repository/about-required-status-checks) to pass, and also require at least one approving review.

**Comment by kvedala** [comment]
good points. Let us ask ourselves:
1. do we foresee, in the current execution, any issues with corrupting the branches? 
2. what value does commit signing add to us? 
3. with #805 merged, status checks are now in place. what additional ones do we need?

Could you answer the above points?

**Comment by Panquesito7** [comment]
> 1. do we foresee, in the current execution, any issues with corrupting the branches?

Something wrong can happen with the branches.
It can happen that, you can corrupt branches when pushing from a different branch, to a different branch with a force-push. That will surely corrupt a branch.

> 2\. what value does commit signing add to us?

You can create commits as another person.
The commit is not verified, and you cannot verify it.

Of course, that is not so common, however you don't know when that can happen.
If the commit is verified, you can trust he is the original committer.

> 3\. with #805 merged, status checks are now in place. what additional ones do we need?

I think you misunderstood my comment.
If you enable the required [status checks](https://help.github.com/en/github/administering-a-repository/about-required-status-checks) option, all checks **must** pass in order to get a PR merged.

**Comment by Panquesito7** [comment]
This has been implemented already.
