### ISSUE TITLE
Confused file name "queue_using_linkedlist"

### ISSUE THREAD

**Issue by volatile-static** [TheAlgorithms/C-Plus-Plus#892]
https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/data_structures/queue_using_linkedlist.cpp

In fact, it's a stack.

**Comment by mishraabhinn** [comment]
I didn't got you. 
<a href="https://www.geeksforgeeks.org/queue-linked-list-implementation/">Refer <a>

**Comment by volatile-static** [comment]
> I didn't got you.
> [Refer ](https://www.geeksforgeeks.org/queue-linked-list-implementation/)

Sorry, I just saw the class names `stack_linkedList `. So I thought it's a stack.
