### ISSUE TITLE
[FEATURE] Code quality checks

### ISSUE THREAD

**Issue by kvedala** [TheAlgorithms/C-Plus-Plus#898]
## Detailed Description

The repo code quality has been quite poor until the introduction of `cpplint` static code analysis checks.
Even then, there are many instances where the checks have not been enough:
1. code formatting is not checked by `cpplint` - introduced `clang-format` in GitHub actions to atuofix formatting per Google C++ standards #805 
2. `cpplint` checks are quite limited and hence a suggestion to use `clang-tidy` was proposed #808 
3. `clang-tidy` would be ideal with following important points to note
    * there is no GUI to view the results 
    * extensive checks and the repo is not unto the standards and would require more effort to fixing it
    * easy to implement the checks only on modified files to mitigate the above problem
    * the above bandaid fix would again cause the repo to be inconsistently formatted code
4. LGTM addresses the two as a mid-way solution
    * it performs more stringent checks than `cpplint` but is more permissive than `clang-tidy`.
    * The output is presented as a convenient GUI for easy views
    * Ability to post a comment on pull-requests after successful checks
    * [List of checks](https://lgtm.com/projects/g/TheAlgorithms/C-Plus-Plus/queries/?pack=com.lgtm%2Fcpp-queries)
    * The parent company of LGTM is to become an integral part of GitHub and hence, I believe a proven and credible platform.
5. There are other tools as discussed in the comments below. 
    * CodeFactor was one
    * Codacy was another and here is my [personal summary](https://github.com/TheAlgorithms/C-Plus-Plus/issues/898#issuecomment-649091521)

Let us discuss the benefits and drawbacks of such an implementation.

~I did create a temporary pull-request for review and discussion #897~ (This now seems redundant)

Please **review thoroughly** and cast your vote on the tool you'd prefer by clicking on that tool below. If selected other, please add a comment mentioning which toll and why.
[![](https://api.gh-polls.com/poll/01EBM5C7JKM20H5EZEDXM0ZKVT/LGTM)](https://api.gh-polls.com/poll/01EBM5C7JKM20H5EZEDXM0ZKVT/LGTM/vote)
[![](https://api.gh-polls.com/poll/01EBM5C7JKM20H5EZEDXM0ZKVT/Codacy)](https://api.gh-polls.com/poll/01EBM5C7JKM20H5EZEDXM0ZKVT/Codacy/vote)
[![](https://api.gh-polls.com/poll/01EBM5C7JKM20H5EZEDXM0ZKVT/CodeFactor)](https://api.gh-polls.com/poll/01EBM5C7JKM20H5EZEDXM0ZKVT/CodeFactor/vote)
[![](https://api.gh-polls.com/poll/01EBM5C7JKM20H5EZEDXM0ZKVT/%60clang-tidy%60%20using%20GiHub%20actions)](https://api.gh-polls.com/poll/01EBM5C7JKM20H5EZEDXM0ZKVT/%60clang-tidy%60%20using%20GiHub%20actions/vote)
[![](https://api.gh-polls.com/poll/01EBM5C7JKM20H5EZEDXM0ZKVT/Other)](https://api.gh-polls.com/poll/01EBM5C7JKM20H5EZEDXM0ZKVT/Other/vote)

**Comment by kvedala** [comment]
@mishraabhinn @ayaankhan98 @AnupKumarPanwar @deadshotsb @Panquesito7 @StepfenShawn @Anmol3299 @iamnambiar

**Comment by ayaankhan98** [comment]
can we use Codacy instead of LGTM?

**Comment by Panquesito7** [comment]
[CodeFactor](https://github.com/marketplace/codefactor/) seems good to me.
It might be a good option.

**Comment by mishraabhinn** [comment]
Is lgtm paid ?

**Comment by Panquesito7** [comment]
> Is LGTM paid ?

No, it's [free](https://github.com/marketplace/lgtm).

**Comment by ayaankhan98** [comment]
> Is lgtm paid ?

**Comment by kvedala** [comment]
> can we use Codacy instead of LGTM?

Please elaborate on your points to make your case for the yet another tool.

**Comment by kvedala** [comment]
> [CodeFactor](https://github.com/marketplace/codefactor/) seems good to me.
> It might be a good option.

Please elaborate on your points to make your case for the yet another tool.

**Comment by Panquesito7** [comment]
> Please elaborate on your points

- Similar to LGTM.
- AFAIK, build runs faster than LGTM.
- Customizable rules.
- Autofix available.
- Supports more programming languages such as:
  - Java.
  - C#.
  - Bash.
  - CSS.
  - And many others.
- Has Slack integration.
- Probably has other stuff I don't know of.

That's my opinion; I think [Code Factor](https://github.com/marketplace/codefactor) is better than [LGTM](https://github.com/marketplace/lgtm). 🙂

**Comment by mishraabhinn** [comment]
<a href="https://medium.com/devgurus/continuous-code-quality-and-automated-code-review-tools-aa911dd1b263">Continuous code quality and automated code review tools
</a>

**Comment by kvedala** [comment]
> > Please elaborate on your points
> 
> * Similar to LGTM.
> * AFAIK, build runs faster than LGTM.
> * Customizable rules.
> * Autofix available.
> * Supports more programming languages such as:
>   
>   * Java.
>   * C#.
>   * Bash.
>   * CSS.
>   * And many others.
> * Has Slack integration.
> * Probably has other stuff I don't know of.
> 
> That's my opinion; I think [Code Factor](https://github.com/marketplace/codefactor) is better than [LGTM](https://github.com/marketplace/lgtm). 🙂

* The more-programming languages option is pretty much useless in this repo - This is exclusively for C++
* [![CodeFactor](https://www.codefactor.io/repository/github/kvedala/c-plus-plus/badge/master)](https://www.codefactor.io/repository/github/kvedala/c-plus-plus/overview/master) This is the current status. so, LGTM is performing more stricter tests than Code Factor.

**Comment by ayaankhan98** [comment]
> > can we use Codacy instead of LGTM?
> 
> Please elaborate on your points to make your case for the yet another tool.

codacy is yet another tool which ensures good code standard, With Codacy, we get static analysis, cyclomatic complexity, duplication and code unit test coverage changes in every commit and pull request.
we can use Codacy to enforce your code quality standard, save time in code reviews, enforce best practices, on integrating with repositories we get quality analysis of every pull request.

apart from this i personally used codacy in some of my repositories i liked it, the GUI is pretty good and provides detailed analysis of everything. we can also define our own settings for pull requests and commits that act as thresholds to our work.

**Comment by ayaankhan98** [comment]
Earlier i tried to link this repository to codacy but it requires admin permission.

**Comment by kvedala** [comment]
### Here is my brief understanding

LGTM | Codacy
-------|----------
convenient for once-in-a-while contributors | not so convenient for once-in-a-while contributors
extremely simple interface for a simple project | too many un-necessary options for a simple project
limited number of checks | extensive checks utilizing existing tools like `clang-tidy`, `cpplint`, etc
no need for additional configuration | needs maintenance and configuration schemes
uses compilation code parameters to analyze code | no compilation and hence finds conflicts between unrelated files that are predominant in our repo
there could be downtimes | so as here
as was observed recently, the servers could crash and result in delayed responses but since there is no emergency to accept pull-requests, we can live with this issue hoping that GitHub takeover can resolve it in future | *unknown to me*

**Comment by kvedala** [comment]
> Earlier i tried to link this repository to codacy but it requires admin permission.

I linked my fork and tried it out

**Comment by ayaankhan98** [comment]
> > Earlier i tried to link this repository to codacy but it requires admin permission.
> 
> I linked my fork and tried it out

so what's the decision are we sticking to LGTM or moving to codacy?

**Comment by kvedala** [comment]
> > > Earlier i tried to link this repository to codacy but it requires admin permission.
> > 
> > 
> > I linked my fork and tried it out
> 
> so what's the decision are we sticking to LGTM or moving to codacy?

Lets wait on more feedback from other members as well. There is no rush to decide on one. The LGTM is active for now anyways and serves the purpose without causing any harm. The thread is essentially for a long term commitment and hence needs to be resolved democratically. I alone cannot make a final decision. Needs to be voted upon.

I have added a voting tool in the main issue description for convenience and easy tracking.

**Comment by kvedala** [comment]
@shubhamguptaji and @ms10398 There was a pull-request #133 merged with the file: `trie_tree.cpp`. This is the only file with the alert that is keeping this repo from getting an **A+** rating. 
* Link to the error: [from lgtm](https://lgtm.com/projects/g/TheAlgorithms/C-Plus-Plus/snapshot/194a3b18c41a6aa46852f64056b0d96e2dcc723b/files/data_structures/trie_tree.cpp?sort=name&dir=ASC&mode=heatmap#x3d34fa30322a5f16:1)
* My comment on the original pull-request: [from GitHub](https://github.com/TheAlgorithms/C-Plus-Plus/pull/133#discussion_r445188624)

**Comment by kvedala** [comment]
After 2 weeks, the majority votes are for LGTM.

**Comment by ayaankhan98** [comment]
> After 2 weeks, the majority votes are for LGTM.

okay let's keep this repo with LGTM
