### ISSUE TITLE
Code in `graph` folder

### ISSUE THREAD

**Issue by kvedala** [TheAlgorithms/C-Plus-Plus#909]
- [x]  is not upto the standards and needs rework
- [x]  include in CMake compilation structure

**Comment by ayaankhan98** [comment]
i am working on this issue

**Comment by kvedala** [comment]
@ayaankhan98 and @fhlasek can this be closed now?

**Comment by fhlasek** [comment]
@kvedala sounds good

**Comment by ayaankhan98** [comment]
Thanks @fhlasek and @kvedala for your continous efforts.
