### ISSUE TITLE
Fenwick Tree[FEATURE]

### ISSUE THREAD

**Issue by enqidu** [TheAlgorithms/C-Plus-Plus#934]
## Detailed Description

 I see that Fenwick Tree implementation is missing.
## Possible Implementation

I can contribute if possible.

**Comment by kvedala** [comment]
are you sure?
https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/range_queries/fenwick_tree.cpp

**Comment by enqidu** [comment]
Oh, thanks, I couldn't find it.
