### ISSUE TITLE
[FEATURE] Adding Fibonacci Search

### ISSUE THREAD

**Issue by sprintyaf** [TheAlgorithms/C-Plus-Plus#938]
I would like to add Fibonacci Search. 

## Description

Fibonacci Search is a comparison-based technique that uses Fibonacci numbers to search an element in a sorted array

## How would it work

Input - a sorted array and an integer
Output - an index of the given integer

**Comment by Panquesito7** [comment]
Please create a PR if you think it fits well here.
We will review your PR as soon as you submit it.

Please review the [contributing guidelines](CONTRIBUTING.md).
Thank you for your contribution. 🙂
