### ISSUE TITLE
[FEATURE] Multilayer Perceptron

### ISSUE THREAD

**Issue by imdeep2905** [TheAlgorithms/C-Plus-Plus#967]
I have seen that you guys have MLP in TODO [here](https://github.com/TheAlgorithms/C-Plus-Plus/projects/1#card-40773519).

I already have implemented NN in C++ ([repo link](https://github.com/imdeep2905/Neural-Network-CPP)). I am planning to make a pull request to add this. But as you might have seen I have created three header files. I am also going to modify code to suit the pull request. Can you please discuss your ideas about what should I do with header files and also some ideas about refactoring my code.

Thanks.

**Comment by kvedala** [comment]
Thats wonderful, thank you 👍 
1. Ideally, the repo had been using at most of two files - one CPP and one H, if needed. 
2. The `matrix.hpp` sounds quite generic and useful. Please review `QR decomposition` and `LU decomposition` programs in the repo that use similar tools but only that are needed. There is redundancy but it keeps the programs whole and easy to read and study with the documentation added and organized using namespaces.

**Comment by imdeep2905** [comment]
I will add proper documentation and namespaces. One more thing should I keep header files in the same folder (```i.e. machine_learning/```).

**Comment by kvedala** [comment]
> I will add proper documentation and namespaces. One more thing should I keep header files in the same folder (`i.e. machine_learning/`).

yes, in the same folder please and with the same names, except for the type suffix - .h and .cpp

**Comment by imdeep2905** [comment]
Is it okay if I provide only ```MSE``` as loss function and ```SGD``` as optimizer (along with various activation functions) ?

**Comment by kvedala** [comment]
> Is it okay if I provide only `MSE` as loss function and `SGD` as optimizer (along with various activation functions) ?

Absolutely!

**Comment by imdeep2905** [comment]
Should I provide facility to save and load model ?
I mean it is already there in my code, but I was confused about that feature since it include file handling (i.e. ```fstream```).

**Comment by kvedala** [comment]
> Should I provide facility to save and load model ?
> I mean it is already there in my code, but I was confused about that feature because it includes file handling (i.e. ```fstream```).

You can use any of the standard C++11 features from the STL library.

**Comment by imdeep2905** [comment]
For testing Can I upload dataset (for e.x. ```iris.csv```) in the same folder ?

**Comment by kvedala** [comment]
I think we can have a small enough CSV file for testing in ML.
Is it https://gist.github.com/curran/a08a1080b88344b0c8a7#file-iris-csv?
Or you can generate simple test data as in other ML programs in the repo and use that for testing.

**Comment by imdeep2905** [comment]
> Is it https://gist.github.com/curran/a08a1080b88344b0c8a7#file-iris-csv?

Yes.
It is only around ```4KB``` in size.

**Comment by kvedala** [comment]
> > Is it https://gist.github.com/curran/a08a1080b88344b0c8a7#file-iris-csv?
> 
> Yes.
> It is only around `4KB` in size.

Ok, sounds fine.
