### ISSUE TITLE
[FEATURE] Add multiplication tables

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C-Plus-Plus#971]
## Detailed Description

Add multiplication tables for any number.
It will show from 1 to 10.

For example, if you type `6`, it will print from `6 * 1` to `6 * 10`.
And the result, of course. 😄

**Comment by kvedala** [comment]
please do not delete the template provided. It enables you to provide with details for what you are requesting and for contributors to better understand the requirements.

This issue has no description whatsoever and does not define what a "multiplication table" is and how it is an algorithm.

**Comment by Panquesito7** [comment]
Updated. Is it OK now?

**Comment by kvedala** [comment]
this doesn't seem like an algorithm. 
closing this.
