### ISSUE TITLE
cpp alg

### ISSUE THREAD

**Issue by RaminCH** [TheAlgorithms/C-Plus-Plus#985]

**Comment by Panquesito7** [comment]
Please provide more information about this issue.
Do not remove the template provided.

Thank you.

**Comment by RaminCH** [comment]
I am learning algorithms and downloaded this app.

On top (+) button on each suggested page seemed like adding interesting topics to my page like to do list (logically).

I think now it isn't right?

Thank you.

**Comment by RaminCH** [comment]
Yup it is actually smthn different.

My apologies.
